import type { Kit } from './kits-types'

export const KITS_E: Kit[] = [

  // —— Rank B ——
  {
    id: 'lofi-linn9000',
    vibe: 'lofi',
    name: 'Linn 9000',
    description: 'Classic Linn 9000 lo-fi pocket',
    bpm: 86,
    drumsBank: 'Linn9000',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ bd ~").bank("Linn9000").gain(0.95)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ ~ ~ sd ~ ~").bank("Linn9000").gain(0.72)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("Linn9000").gain(0.28).lpf(4400)' },
      { name: 'Keys', role: 'pad', code: 'note("<[c3,eb3,g3] [f3,ab3,c4]>").sound("triangle").room(0.45).lpf(1300).gain(0.28)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ f2 ~>").sound("sine").lpf(280).gain(0.55)' },
    ],
  },
  {
    id: 'techno-ry30',
    vibe: 'techno',
    name: 'RY-30 Edge',
    description: 'Punchy Yamaha RY-30 dance',
    bpm: 128,
    drumsBank: 'YamahaRY30',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("YamahaRY30").n(0).gain(1.18)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("YamahaRY30").n(0).gain(0.38)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("YamahaRY30").gain(0.82)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 eb2 f2 g2>").sound("sawtooth").lpf(600).gain(0.7)' },
      { name: 'Lead', role: 'lead', code: 'note("<c4 ~ eb4 g4>*2").sound("square").delay(0.2).gain(0.22)' },
    ],
  },
  {
    id: 'techno-jd990',
    vibe: 'techno',
    name: 'JD-990 Dance',
    description: 'Roland JD-990 dance kit',
    bpm: 128,
    drumsBank: 'RolandJD990',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("RolandJD990").n(0).gain(1.16)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("RolandJD990").n(0).gain(0.36)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("RolandJD990").gain(0.8)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 c2 eb2 g1>").sound("sawtooth").lpf(700).lpq(8).gain(0.7)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,eb3,g3]").sound("triangle").lpf(650).room(0.4).gain(0.24)' },
    ],
  },
  {
    id: 'house-dpm48',
    vibe: 'house',
    name: 'DPM-48',
    description: 'Sakata DPM-48 Japanese house kit',
    bpm: 120,
    drumsBank: 'SakataDPM48',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("SakataDPM48").n(0).gain(1.12)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("SakataDPM48").gain(0.4)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("SakataDPM48").gain(0.78)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 c2 g1 g1>").sound("sawtooth").lpf(480).gain(0.66)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,e3,g3]").sound("sine").room(0.35).gain(0.22)' },
    ],
  },
  {
    id: 'techno-mfb512',
    vibe: 'techno',
    name: 'MFB-512',
    description: 'Tight MFB-512 analog-ish techno',
    bpm: 128,
    drumsBank: 'MFB512',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("MFB512").gain(1.2)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("MFB512").gain(0.35).hpf(5000)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("MFB512").gain(0.8)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~>").sound("square").lpf(450).gain(0.7)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 ~ g4 ~>").sound("triangle").delay(0.25).gain(0.2)' },
    ],
  },
  {
    id: 'lofi-hr16',
    vibe: 'lofi',
    name: 'HR-16 Soft',
    description: 'Soft Alesis HR-16 companion',
    bpm: 88,
    drumsBank: 'AlesisHR16',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ bd ~").bank("AlesisHR16").gain(0.92)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ ~ ~ sd ~ ~").bank("AlesisHR16").gain(0.7)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("AlesisHR16").gain(0.26).lpf(4000)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,e3,g3] [a2,c3,e3]>").sound("sine").room(0.55).gain(0.28)' },
      { name: 'Bass', role: 'bass', code: 'note("c2 ~ g1 ~ eb2 ~ f2 ~").sound("triangle").lpf(300).gain(0.5)' },
    ],
  },
  {
    id: 'ambient-dr220',
    vibe: 'ambient',
    name: 'DR-220 Soft',
    description: 'Soft Boss DR-220 ambient pulse',
    bpm: 68,
    drumsBank: 'BossDR220',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ ~").bank("BossDR220").gain(0.42).lpf(700)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ ~").bank("BossDR220").gain(0.16).room(0.6)' },
      { name: 'Ride', role: 'fx', code: 's("~ ~ rd ~").bank("BossDR220").room(0.7).gain(0.22)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,eb3,g3] [f3,ab3,c4]>").sound("sine").room(0.9).attack(0.7).gain(0.3)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ ~ ~>").sound("sine").lpf(180).attack(0.4).gain(0.38)' },
    ],
  },
  {
    id: 'house-cr1000',
    vibe: 'house',
    name: 'CR-1000 Disco',
    description: 'Roland CR-1000 disco four-on-floor',
    bpm: 116,
    drumsBank: 'RolandCompurhythm1000',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("RolandCompurhythm1000").gain(1.05)' },
      { name: 'Hats', role: 'hihats', code: 's("hh hh oh hh").bank("RolandCompurhythm1000").gain(0.42)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("RolandCompurhythm1000").gain(0.7)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ f2 ~ g2 ~ eb2 ~>").sound("triangle").lpf(520).gain(0.6)' },
      { name: 'Keys', role: 'lead', code: 'note("<c4 e4 g4 a4>").sound("square").lpf(2000).room(0.25).gain(0.2)' },
    ],
  },
  {
    id: 'lofi-cr8000',
    vibe: 'lofi',
    name: 'CR-8000 Tape',
    description: 'Vintage CR-8000 tape texture',
    bpm: 82,
    drumsBank: 'RolandCompurhythm8000',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ bd ~").bank("RolandCompurhythm8000").gain(0.9)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ hh").bank("RolandCompurhythm8000").gain(0.34).lpf(3500)' },
      { name: 'Clap', role: 'fx', code: 's("~ ~ cp ~").bank("RolandCompurhythm8000").room(0.4).gain(0.5)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,eb3,g3,bb3] [f3,ab3,c4]>").sound("sine").room(0.8).attack(0.3).gain(0.25)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~>").sound("sine").lpf(250).gain(0.58)' },
    ],
  },
  {
    id: 'techno-space-drum',
    vibe: 'techno',
    name: 'Space Drum',
    description: 'Visco Space Drum synth-tom techno',
    bpm: 128,
    drumsBank: 'ViscoSpaceDrum',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("ViscoSpaceDrum").n(0).gain(1.15)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("ViscoSpaceDrum").n(0).gain(0.35)' },
      { name: 'Tom', role: 'fx', code: 's("~ ht ~ mt").bank("ViscoSpaceDrum").room(0.3).gain(0.65)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 eb2 f2 g2>").sound("sawtooth").lpf(550).gain(0.7)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 ~ g4 ~>").sound("square").delay(0.3).gain(0.2)' },
    ],
  },
  {
    id: 'house-m1-drums',
    vibe: 'house',
    name: 'M1 Drums',
    description: 'Korg M1 workstation house drums',
    bpm: 120,
    drumsBank: 'KorgM1',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("KorgM1").n(0).gain(1.12)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("KorgM1").gain(0.4)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("KorgM1").gain(0.78)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~ f2 ~ g2 ~>").sound("sawtooth").lpf(500).gain(0.66)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,e3,g3]").sound("triangle").room(0.35).gain(0.22)' },
    ],
  },
  {
    id: 'lofi-rx5',
    vibe: 'lofi',
    name: 'RX-5 Grain',
    description: 'Classic Yamaha RX-5 grain',
    bpm: 90,
    drumsBank: 'YamahaRX5',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ bd ~ ~ bd ~ ~").bank("YamahaRX5").n(0).gain(0.95)' },
      { name: 'Rim', role: 'fx', code: 's("~ rim ~ ~ rim ~ ~ ~").bank("YamahaRX5").gain(0.5)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("YamahaRX5").gain(0.26).lpf(4200)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,e3,g3] [a2,c3,e3]>").sound("triangle").room(0.55).lpf(1300).gain(0.28)' },
      { name: 'Bass', role: 'bass', code: 'note("c2 ~ g1 ~ eb2 ~ f2 ~").sound("sawtooth").lpf(360).gain(0.5)' },
    ],
  },
  {
    id: 'ambient-rx21',
    vibe: 'ambient',
    name: 'RX-21 Soft',
    description: 'Soft Yamaha RX-21 ambient',
    bpm: 66,
    drumsBank: 'YamahaRX21',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ ~").bank("YamahaRX21").gain(0.4).lpf(700)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ ~").bank("YamahaRX21").gain(0.16).room(0.55)' },
      { name: 'Clap', role: 'fx', code: 's("~ ~ cp ~").bank("YamahaRX21").room(0.7).gain(0.22)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,e3,g3] [d3,f3,a3]>").sound("sine").room(0.9).attack(0.6).gain(0.3)' },
      { name: 'Bass', role: 'bass', code: 'note("c2").sound("sine").lpf(180).gain(0.35)' },
    ],
  },
  {
    id: 'house-mt32',
    vibe: 'house',
    name: 'MT-32 Kit',
    description: 'Roland MT-32 LA-synth GM drums',
    bpm: 120,
    drumsBank: 'RolandMT32',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("RolandMT32").gain(1.1)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("RolandMT32").gain(0.38)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("RolandMT32").gain(0.78)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 c2 g1 g1>").sound("sawtooth").lpf(480).gain(0.66)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,e3,g3]").sound("sine").room(0.35).gain(0.22)' },
    ],
  },
  {
    id: 'house-gretsch',
    vibe: 'house',
    name: 'Gretsch Kit',
    description: 'Dirt Gretsch acoustic house feel',
    bpm: 118,
    drumsBank: 'dirt-gretsch',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("gretsch:0*4").gain(1.05)' },
      { name: 'Hats', role: 'hihats', code: 's("gretsch:2*8").gain(0.35)' },
      { name: 'Snare', role: 'fx', code: 's("~ gretsch:1 ~ gretsch:1").gain(0.75)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~ f2 ~ g2 ~>").sound("sawtooth").lpf(500).gain(0.66)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,e3,g3]").sound("triangle").room(0.35).gain(0.22)' },
    ],
  },
  {
    id: 'techno-dirt-electro',
    vibe: 'techno',
    name: 'Dirt Electro',
    description: 'Dirt electro1 techno kit',
    bpm: 128,
    drumsBank: 'dirt-electro',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("electro1:0*4").gain(1.15)' },
      { name: 'Hats', role: 'hihats', code: 's("electro1:2*8").gain(0.35).hpf(5000)' },
      { name: 'Snare', role: 'fx', code: 's("~ electro1:1 ~ electro1:1").gain(0.8)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 eb2 f2 g2>").sound("square").lpf(500).gain(0.7)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 ~ g4 ~>").sound("sawtooth").lpf(1800).delay(0.25).gain(0.2)' },
    ],
  },
  {
    id: 'lofi-vcsl-kit',
    vibe: 'lofi',
    name: 'VCSL Kit',
    description: 'VCSL acoustic cluster lo-fi (CPU soft-load)',
    bpm: 86,
    drumsBank: 'vcsl',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bassdrum1 ~ ~ bassdrum2 ~ ~ bassdrum1 ~").gain(0.9)' },
      { name: 'Snare', role: 'fx', code: 's("~ snare_modern ~ ~ ~ snare_low ~ ~").gain(0.7)' },
      { name: 'Hats', role: 'hihats', code: 's("hihat*8").gain(0.28).lpf(5000)' },
      { name: 'Keys', role: 'pad', code: 'note("<[c3,eb3,g3] [f3,ab3,c4]>").sound("kalimba").room(0.5).gain(0.26)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ f2 ~>").sound("sine").lpf(280).gain(0.55)' },
    ],
  },
  {
    id: 'ambient-piano-room',
    vibe: 'ambient',
    name: 'Piano Room',
    description: 'Dedicated piano lead/pad room (CPU soft-load)',
    bpm: 70,
    drumsBank: 'piano',
    tracks: [
      { name: 'Pulse', role: 'drums', code: 's("bd ~ ~ ~").gain(0.35).lpf(600)' },
      { name: 'Shimmer', role: 'hihats', code: 's("~ hh ~ ~").gain(0.12).room(0.7)' },
      { name: 'Piano', role: 'pad', code: 'note("<[c3,e3,g3] [d3,f3,a3]>").sound("piano").room(0.9).attack(0.4).gain(0.32)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 ~ e5 ~ g5 ~>").sound("piano").room(0.7).gain(0.16)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ ~ ~>").sound("sine").lpf(180).attack(0.4).gain(0.38)' },
    ],
  },
  {
    id: 'techno-clean-breaks',
    vibe: 'techno',
    name: 'Clean Breaks',
    description: 'Clean break chops (dirt breaks fallback)',
    bpm: 165,
    drumsBank: 'clean-breaks',
    tracks: [
      { name: 'Break', role: 'drums', code: 's("breaks165:0 breaks165:1 breaks165:2 breaks165:3").gain(0.92)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*16").gain(0.2).hpf(6000)' },
      { name: 'Chop', role: 'fx', code: 's("~ breaks157:2 ~ breaks157:4").room(0.15).gain(0.65)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~ g1 ~>").sound("sawtooth").lpf(400).gain(0.72)' },
      { name: 'Stab', role: 'lead', code: 'note("<c4 ~ g4 ~>").sound("square").lpf(1700).delay(0.15).gain(0.2)' },
    ],
  },
]
