import type { Kit } from './kits-types'

export const KITS_F: Kit[] = [

  // —— Usable Rank C ——
  {
    id: 'techno-system100',
    vibe: 'techno',
    name: 'System 100',
    description: 'Roland System 100 modular clicks',
    bpm: 128,
    drumsBank: 'RolandSystem100',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("RolandSystem100").n(0).gain(1.1)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("RolandSystem100").gain(0.34)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ sd").bank("RolandSystem100").n(0).gain(0.75)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~>").sound("square").lpf(450).gain(0.68)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 ~ g4 ~>").sound("triangle").delay(0.3).gain(0.18)' },
    ],
  },
  {
    id: 'lofi-rhythm-ace',
    vibe: 'lofi',
    name: 'Rhythm Ace',
    description: 'Ace auto-rhythm lo-fi character',
    bpm: 84,
    drumsBank: 'RhythmAce',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ bd ~").bank("RhythmAce").n(0).gain(0.9)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ ~ ~ sd ~ ~").bank("RhythmAce").n(0).gain(0.68)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("RhythmAce").gain(0.28).lpf(4000)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,eb3,g3] [f3,ab3,c4]>").sound("sine").room(0.5).gain(0.26)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~>").sound("triangle").lpf(280).gain(0.52)' },
    ],
  },
  {
    id: 'techno-ms404',
    vibe: 'techno',
    name: 'MS-404',
    description: 'Doepfer MS-404 acid-box drums',
    bpm: 130,
    drumsBank: 'DoepferMS404',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("DoepferMS404").n(0).gain(1.15)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("DoepferMS404").gain(0.34).hpf(5000)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ sd").bank("DoepferMS404").gain(0.78)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 c2 eb2 g1>").sound("sawtooth").lpf(900).lpq(14).gain(0.72)' },
      { name: 'Lead', role: 'lead', code: 'note("<c4 ~ eb4 g4>*2").sound("square").lpf(2000).delay(0.2).gain(0.2)' },
    ],
  },
  {
    id: 'techno-sc-tom',
    vibe: 'techno',
    name: 'SC Tom',
    description: 'Sequential Circuits Tom punch',
    bpm: 128,
    drumsBank: 'SequentialCircuitsTom',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("SequentialCircuitsTom").gain(1.15)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("SequentialCircuitsTom").gain(0.36)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("SequentialCircuitsTom").gain(0.8)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 eb2 f2 g2>").sound("sawtooth").lpf(580).gain(0.7)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,eb3,g3]").sound("triangle").lpf(650).room(0.35).gain(0.24)' },
    ],
  },
  {
    id: 'lofi-jazz-kit',
    vibe: 'lofi',
    name: 'Jazz Kit',
    description: 'Dirt jazz acoustic-ish pocket',
    bpm: 90,
    drumsBank: 'dirt-jazz',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("jazz:0 ~ ~ jazz:0 ~ jazz:0 ~ ~").gain(0.9)' },
      { name: 'Snare', role: 'fx', code: 's("~ jazz:1 ~ ~ ~ jazz:1 ~ ~").gain(0.7)' },
      { name: 'Hats', role: 'hihats', code: 's("jazz:2*8").gain(0.28).lpf(5000)' },
      { name: 'Keys', role: 'pad', code: 'note("<[c3,e3,g3] [a2,c3,e3]>").sound("piano").lpf(1600).room(0.45).gain(0.28)' },
      { name: 'Bass', role: 'bass', code: 'note("c2 ~ g1 ~ eb2 ~ f2 ~").sound("sine").lpf(280).gain(0.52)' },
    ],
  },
  {
    id: 'lofi-casio-sk1',
    vibe: 'lofi',
    name: 'Casio SK-1',
    description: 'Toy Casio SK-1 lo-fi swing',
    bpm: 82,
    drumsBank: 'CasioSK1',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ ~ ~").bank("CasioSK1").gain(0.88)' },
      { name: 'Snare', role: 'fx', code: 's("~ ~ sd ~ ~ ~ sd ~").bank("CasioSK1").gain(0.55)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ hh").bank("CasioSK1").gain(0.32).lpf(3800)' },
      { name: 'Piano', role: 'pad', code: 'note("<[c3,eb3,g3] [ab2,c3,eb3]>").sound("piano").room(0.55).attack(0.08).gain(0.26)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~>").sound("triangle").lpf(300).gain(0.5)' },
    ],
  },
  {
    id: 'lofi-kr55',
    vibe: 'lofi',
    name: 'KR-55',
    description: 'Korg KR-55 vintage auto-rhythm',
    bpm: 84,
    drumsBank: 'KorgKR55',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ bd ~").bank("KorgKR55").gain(0.9)' },
      { name: 'Rim', role: 'fx', code: 's("~ rim ~ ~ rim ~ ~ ~").bank("KorgKR55").gain(0.5)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("KorgKR55").gain(0.28).lpf(4200)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,eb3,g3] [f3,ab3,c4]>").sound("sine").room(0.5).gain(0.26)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ f2 ~>").sound("triangle").lpf(280).gain(0.52)' },
    ],
  },
  {
    id: 'techno-uzu-waves',
    vibe: 'techno',
    name: 'Uzu Waves',
    description: 'Uzu wavetable melodic techno',
    bpm: 128,
    drumsBank: 'uzu-wt',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").gain(1.1)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").gain(0.3).hpf(5500)' },
      { name: 'Wave', role: 'lead', code: 's("wt_digital").note("<c3 eb3 g3 bb3>*2").gain(0.35).lpf(2000)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 c2 eb2 g1>").sound("sawtooth").lpf(700).lpq(10).gain(0.7)' },
      { name: 'Pad', role: 'pad', code: 's("wt_vgame").note("[c3,eb3,g3]").room(0.45).gain(0.22)' },
    ],
  },
  {
    id: 'ambient-vcsl-keys',
    vibe: 'ambient',
    name: 'VCSL Keys',
    description: 'VCSL marimba/kalimba ambient keys',
    bpm: 68,
    drumsBank: 'vcsl-keys',
    tracks: [
      { name: 'Pulse', role: 'drums', code: 's("bassdrum1 ~ ~ ~").gain(0.35).lpf(650)' },
      { name: 'Shimmer', role: 'hihats', code: 's("~ hihat ~ ~").gain(0.12).room(0.6)' },
      { name: 'Marimba', role: 'pad', code: 'note("<[c3,e3,g3] [d3,f3,a3]>").sound("marimba").room(0.85).attack(0.2).gain(0.3)' },
      { name: 'Kalimba', role: 'lead', code: 'note("<c5 ~ e5 ~ g5 ~>").sound("kalimba").room(0.7).gain(0.18)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ ~ ~>").sound("sine").lpf(180).attack(0.4).gain(0.38)' },
    ],
  },
  {
    id: 'ambient-vcsl-organ',
    vibe: 'ambient',
    name: 'VCSL Organ',
    description: 'VCSL organ pad ambient wash',
    bpm: 64,
    drumsBank: 'vcsl-organ',
    tracks: [
      { name: 'Pulse', role: 'drums', code: 's("bassdrum2 ~ ~ ~ ~ ~ ~ ~").gain(0.32).lpf(600)' },
      { name: 'Air', role: 'hihats', code: 's("~ hihat ~ ~").gain(0.1).room(0.7)' },
      { name: 'Organ', role: 'pad', code: 'note("<[c2,g2,c3] [f2,c3,f3]>").sound("organ_8inch").room(0.95).attack(0.9).gain(0.32)' },
      { name: 'Pipe', role: 'lead', code: 'note("<c4 ~ e4 ~>").sound("pipeorgan_quiet").room(0.8).gain(0.14)' },
      { name: 'Bass', role: 'bass', code: 'note("<c1 ~ ~ ~>").sound("sine").lpf(150).attack(0.5).gain(0.4)' },
    ],
  },
  {
    id: 'ambient-tabla',
    vibe: 'ambient',
    name: 'Tabla Circle',
    description: 'Dirt tabla melodic perc circles',
    bpm: 72,
    drumsBank: 'dirt-tabla',
    tracks: [
      { name: 'Tabla', role: 'drums', code: 's("tabla:0 ~ tabla:2 ~ tabla:4 ~ tabla:1 ~").gain(0.7).room(0.35)' },
      { name: 'Tabla2', role: 'hihats', code: 's("~ tabla2:1 ~ tabla2:3").gain(0.4).room(0.4)' },
      { name: 'Hit', role: 'fx', code: 's("~ ~ tablex:0 ~").room(0.5).gain(0.35)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,eb3,g3,bb3] [ab2,c3,eb3,g3]>").sound("sine").room(0.9).attack(0.7).gain(0.3)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ ~ ~>").sound("sine").lpf(180).attack(0.4).gain(0.38)' },
    ],
  },
]
