import type { Kit } from './kits-types'

export const KITS_D: Kit[] = [

  // —— House ——
  {
    id: 'house-lm2-pocket',
    vibe: 'house',
    name: 'LM-2 Pocket',
    description: 'Punchy Linn LM-2 house pocket',
    bpm: 120,
    drumsBank: 'LinnLM2',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'dry',
    },
  },

  // —— Techno ——
  {
    id: 'techno-drumulator',
    vibe: 'techno',
    name: 'Drumulator Punch',
    description: 'Tight E-mu Drumulator techno',
    bpm: 128,
    drumsBank: 'EmuDrumulator',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-drumtraks',
    vibe: 'lofi',
    name: 'DrumTraks Dust',
    description: 'Sequential DrumTraks dusty pocket',
    bpm: 86,
    drumsBank: 'SequentialCircuitsDrumtracks',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sine'],
      fxBias: 'roomy',
    },
  },

  // —— House ——
  {
    id: 'house-r8-classic',
    vibe: 'house',
    name: 'R-8 Classic',
    description: 'Late-80s Roland R-8 house',
    bpm: 122,
    drumsBank: 'RolandR8',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'dry',
    },
  },

  // —— Techno ——
  {
    id: 'techno-simmons',
    vibe: 'techno',
    name: 'Simmons SDS5',
    description: 'Electronic Simmons SDS5 punch',
    bpm: 130,
    drumsBank: 'SimmonsSDS5',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },

  // —— House ——
  {
    id: 'house-dr550',
    vibe: 'house',
    name: 'DR-550 Groove',
    description: 'Boss DR-550 modern house groove',
    bpm: 120,
    drumsBank: 'BossDR550',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'dry',
      pinN: 0,
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-sr16',
    vibe: 'lofi',
    name: 'SR-16 Tape',
    description: 'Warm Alesis SR-16 studio tape',
    bpm: 88,
    drumsBank: 'AlesisSR16',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['piano', 'triangle'],
      fxBias: 'roomy',
      pinN: 0,
    },
  },

  // —— House ——
  {
    id: 'house-626-groove',
    vibe: 'house',
    name: '626 Groove',
    description: 'TR-626 perc-friendly house',
    bpm: 120,
    drumsBank: 'RolandTR626',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'dry',
    },
  },

  // —— Techno ——
  {
    id: 'techno-uzu-core',
    vibe: 'techno',
    name: 'Uzu Core',
    description: 'Modern uzu-drumkit techno core',
    bpm: 128,
    drumsBank: 'uzu',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'filtered',
    },
  },
  {
    id: 'techno-amen-chop',
    vibe: 'techno',
    name: 'Amen Chop',
    description: 'Dirt amencutup jungle chops',
    bpm: 170,
    drumsBank: 'dirt-amen',
    tracks: [
      { name: 'Break', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Chop', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Stab', role: 'lead' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'high',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
    },
  },

  // —— Ambient ——
  {
    id: 'ambient-mridangam',
    vibe: 'ambient',
    name: 'Mridangam Circles',
    description: 'South-Indian mridangam ambient circles',
    bpm: 70,
    drumsBank: 'mridangam',
    tracks: [
      { name: 'Tha', role: 'drums' },
      { name: 'Nam', role: 'hihats' },
      { name: 'Chaapu', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'perc_loop',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },

  // —— House ——
  {
    id: 'house-xr10',
    vibe: 'house',
    name: 'XR-10 House',
    description: 'Akai XR-10 full house kit',
    bpm: 118,
    drumsBank: 'AkaiXR10',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'dry',
      pinN: 0,
    },
  },
  {
    id: 'house-rm50-studio',
    vibe: 'house',
    name: 'RM-50 Studio',
    description: 'Curated Yamaha RM-50 studio house (n=0)',
    bpm: 122,
    drumsBank: 'YamahaRM50',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'dry',
      pinN: 0,
    },
  },

  // —— Techno ——
  {
    id: 'techno-mc303',
    vibe: 'techno',
    name: 'MC-303 Groove',
    description: 'Curated Roland MC-303 groovebox techno (n=0)',
    bpm: 130,
    drumsBank: 'RolandMC303',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },
]
