import type { TrackRole } from './types'
import type { SoundChoice } from './kits-types'

export const MELODIC_SOUND_CHOICES: Partial<Record<TrackRole, SoundChoice[]>> = {
  bass: [
    { id: 'saw', label: 'Saw bass', sound: 'sawtooth' },
    { id: 'square', label: 'Square bass', sound: 'square' },
    { id: 'sine', label: 'Sine sub', sound: 'sine' },
    { id: 'tri', label: 'Triangle', sound: 'triangle' },
    { id: 'piano-bass', label: 'Piano bass', sound: 'piano' },
    { id: 'bass', label: 'Dirt bass', sound: 'bass' },
    { id: 'jvbass', label: 'JV bass', sound: 'jvbass' },
    { id: 'wobble', label: 'Wobble', sound: 'wobble' },
    { id: 'jungbass', label: 'Jungle bass', sound: 'jungbass' },
  ],
  lead: [
    { id: 'square', label: 'Square lead', sound: 'square' },
    { id: 'saw', label: 'Saw lead', sound: 'sawtooth' },
    { id: 'tri', label: 'Soft tri', sound: 'triangle' },
    { id: 'sine', label: 'Sine lead', sound: 'sine' },
    { id: 'piano', label: 'Piano lead', sound: 'piano' },
    { id: 'marimba', label: 'Marimba', sound: 'marimba' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    { id: 'pipeorgan-quiet', label: 'Pipe organ quiet', sound: 'pipeorgan_quiet' },
    { id: 'organ-8inch', label: 'Organ 8 inch', sound: 'organ_8inch' },
    { id: 'organ-full', label: 'Organ full', sound: 'organ_full' },
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
    { id: 'wt-vgame', label: 'WT vgame', sound: 'wt_vgame' },
    { id: 'sax', label: 'Sax', sound: 'sax' },
    { id: 'gtr', label: 'Guitar', sound: 'gtr' },
    { id: 'pluck', label: 'Pluck', sound: 'pluck' },
    { id: 'arpy', label: 'Arpy', sound: 'arpy' },
    { id: 'juno', label: 'Juno', sound: 'juno' },
    { id: 'stab', label: 'Stab', sound: 'stab' },
    { id: 'hoover', label: 'Hoover', sound: 'hoover' },
  ],
  pad: [
    { id: 'sine', label: 'Sine pad', sound: 'sine' },
    { id: 'tri', label: 'Tri pad', sound: 'triangle' },
    { id: 'saw', label: 'Saw pad', sound: 'sawtooth' },
    { id: 'square', label: 'Square pad', sound: 'square' },
    { id: 'piano', label: 'Piano room', sound: 'piano' },
    { id: 'organ-wash', label: 'Organ wash', sound: 'organ_8inch' },
    { id: 'pipeorgan', label: 'Pipe organ', sound: 'pipeorgan_quiet' },
    { id: 'vcsl-organ', label: 'VCSL organ', sound: 'organ_full' },
    { id: 'marimba-pad', label: 'Marimba pad', sound: 'marimba' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    { id: 'pad', label: 'Dirt pad', sound: 'pad' },
    { id: 'padlong', label: 'Pad long', sound: 'padlong' },
    { id: 'wt-vgame', label: 'WT pad', sound: 'wt_vgame' },
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
  ],
  arp: [
    { id: 'tri', label: 'Tri arp', sound: 'triangle' },
    { id: 'sine', label: 'Sine arp', sound: 'sine' },
    { id: 'square', label: 'Square arp', sound: 'square' },
    { id: 'saw', label: 'Saw arp', sound: 'sawtooth' },
    { id: 'piano', label: 'Piano arp', sound: 'piano' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    { id: 'marimba', label: 'Marimba', sound: 'marimba' },
    { id: 'pluck', label: 'Pluck', sound: 'pluck' },
    { id: 'arpy', label: 'Arpy', sound: 'arpy' },
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
  ],
  vox: [
    { id: 'hmm', label: 'Hmm', sound: 'hmm' },
    { id: 'speechless', label: 'Speech', sound: 'speechless' },
    { id: 'breath', label: 'Breath', sound: 'breath' },
    { id: 'diphone', label: 'Diphone', sound: 'diphone' },
  ],
  custom: [
    { id: 'saw', label: 'Saw', sound: 'sawtooth' },
    { id: 'sine', label: 'Sine', sound: 'sine' },
    { id: 'piano', label: 'Piano', sound: 'piano' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    { id: 'marimba', label: 'Marimba', sound: 'marimba' },
    { id: 'organ-8inch', label: 'Organ 8 inch', sound: 'organ_8inch' },
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
    { id: 'wt-vgame', label: 'WT vgame', sound: 'wt_vgame' },
  ]
}
