import type { Kit } from './kits-types'

export const KITS_B: Kit[] = [

  // —— Ambient ——
  {
    id: 'ambient-soft-sine',
    vibe: 'ambient',
    name: 'Soft Sine',
    description: 'Sparse pulse + wide pads',
    bpm: 70,
    drumsBank: 'RolandCompurhythm78',
    tracks: [
      { name: 'Pulse', role: 'drums' },
      { name: 'Shimmer', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine', 'triangle'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-drone909',
    vibe: 'ambient',
    name: 'Drone 909',
    description: 'Distant 909 + evolving wash',
    bpm: 75,
    drumsBank: 'RolandTR909',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Arp', role: 'arp' },
      { name: 'FX', role: 'fx' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-linn-mist',
    vibe: 'ambient',
    name: 'Linn Mist',
    description: 'Soft percussion haze',
    bpm: 68,
    drumsBank: 'LinnDrum',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['triangle', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-808-bloom',
    vibe: 'ambient',
    name: '808 Bloom',
    description: 'Sub bloom + airy hats',
    bpm: 72,
    drumsBank: 'RolandTR808',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
      { name: 'FX', role: 'fx' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },

  // —— House ——
  {
    id: 'house-classic909',
    vibe: 'house',
    name: 'Classic 909',
    description: 'Four-on-floor 909 house',
    bpm: 122,
    drumsBank: 'RolandTR909',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'dry',
    },
  },
  {
    id: 'house-chic808',
    vibe: 'house',
    name: 'Chic 808',
    description: 'Disco-tinged 808',
    bpm: 118,
    drumsBank: 'RolandTR808',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'dry',
    },
  },
  {
    id: 'house-linn-groove',
    vibe: 'house',
    name: 'Linn Groove',
    description: 'Organic house pocket',
    bpm: 120,
    drumsBank: 'LinnDrum',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'dry',
    },
  },
  {
    id: 'house-cr78-disco',
    vibe: 'house',
    name: 'CR78 Disco',
    description: 'Retro four-on-floor',
    bpm: 116,
    drumsBank: 'RolandCompurhythm78',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['triangle', 'square'],
      fxBias: 'dry',
    },
  },

  // —— Techno ——
  {
    id: 'techno-acid707',
    vibe: 'techno',
    name: 'Acid 707',
    description: 'Sharp TR-707 techno with acid bass',
    bpm: 132,
    drumsBank: 'RolandTR707',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'high',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
    },
  },
]
