import type { Kit } from './kits-types'

export const KITS_E: Kit[] = [

  // —— Lo-fi ——
  {
    id: 'lofi-linn9000',
    vibe: 'lofi',
    name: 'Linn 9000',
    description: 'Classic Linn 9000 lo-fi pocket',
    bpm: 86,
    drumsBank: 'Linn9000',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sine'],
      fxBias: 'roomy',
    },
  },

  // —— Techno ——
  {
    id: 'techno-ry30',
    vibe: 'techno',
    name: 'RY-30 Edge',
    description: 'Punchy Yamaha RY-30 dance',
    bpm: 128,
    drumsBank: 'YamahaRY30',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },
  {
    id: 'techno-jd990',
    vibe: 'techno',
    name: 'JD-990 Dance',
    description: 'Roland JD-990 dance kit',
    bpm: 128,
    drumsBank: 'RolandJD990',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },

  // —— House ——
  {
    id: 'house-dpm48',
    vibe: 'house',
    name: 'DPM-48',
    description: 'Sakata DPM-48 Japanese house kit',
    bpm: 120,
    drumsBank: 'SakataDPM48',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'dry',
      pinN: 0,
    },
  },

  // —— Techno ——
  {
    id: 'techno-mfb512',
    vibe: 'techno',
    name: 'MFB-512',
    description: 'Tight MFB-512 analog-ish techno',
    bpm: 128,
    drumsBank: 'MFB512',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'filtered',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-hr16',
    vibe: 'lofi',
    name: 'HR-16 Soft',
    description: 'Soft Alesis HR-16 companion',
    bpm: 88,
    drumsBank: 'AlesisHR16',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine', 'triangle'],
      fxBias: 'roomy',
    },
  },

  // —— Ambient ——
  {
    id: 'ambient-dr220',
    vibe: 'ambient',
    name: 'DR-220 Soft',
    description: 'Soft Boss DR-220 ambient pulse',
    bpm: 68,
    drumsBank: 'BossDR220',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Ride', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },

  // —— House ——
  {
    id: 'house-cr1000',
    vibe: 'house',
    name: 'CR-1000 Disco',
    description: 'Roland CR-1000 disco four-on-floor',
    bpm: 116,
    drumsBank: 'RolandCompurhythm1000',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['triangle', 'square'],
      fxBias: 'dry',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-cr8000',
    vibe: 'lofi',
    name: 'CR-8000 Tape',
    description: 'Vintage CR-8000 tape texture',
    bpm: 82,
    drumsBank: 'RolandCompurhythm8000',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },

  // —— Techno ——
  {
    id: 'techno-space-drum',
    vibe: 'techno',
    name: 'Space Drum',
    description: 'Visco Space Drum synth-tom techno',
    bpm: 128,
    drumsBank: 'ViscoSpaceDrum',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Tom', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },

  // —— House ——
  {
    id: 'house-m1-drums',
    vibe: 'house',
    name: 'M1 Drums',
    description: 'Korg M1 workstation house drums',
    bpm: 120,
    drumsBank: 'KorgM1',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'dry',
      pinN: 0,
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-rx5',
    vibe: 'lofi',
    name: 'RX-5 Grain',
    description: 'Classic Yamaha RX-5 grain',
    bpm: 90,
    drumsBank: 'YamahaRX5',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Rim', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sawtooth'],
      fxBias: 'roomy',
      pinN: 0,
    },
  },

  // —— Ambient ——
  {
    id: 'ambient-rx21',
    vibe: 'ambient',
    name: 'RX-21 Soft',
    description: 'Soft Yamaha RX-21 ambient',
    bpm: 66,
    drumsBank: 'YamahaRX21',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },

  // —— House ——
  {
    id: 'house-mt32',
    vibe: 'house',
    name: 'MT-32 Kit',
    description: 'Roland MT-32 LA-synth GM drums',
    bpm: 120,
    drumsBank: 'RolandMT32',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'dry',
    },
  },
  {
    id: 'house-gretsch',
    vibe: 'house',
    name: 'Gretsch Kit',
    description: 'Dirt Gretsch acoustic house feel',
    bpm: 118,
    drumsBank: 'dirt-gretsch',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'dry',
    },
  },

  // —— Techno ——
  {
    id: 'techno-dirt-electro',
    vibe: 'techno',
    name: 'Dirt Electro',
    description: 'Dirt electro1 techno kit',
    bpm: 128,
    drumsBank: 'dirt-electro',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['square', 'sawtooth'],
      fxBias: 'filtered',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-vcsl-kit',
    vibe: 'lofi',
    name: 'VCSL Kit',
    description: 'VCSL acoustic cluster lo-fi (CPU soft-load)',
    bpm: 86,
    drumsBank: 'vcsl',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['kalimba', 'sine', 'triangle'],
      fxBias: 'roomy',
    },
  },

  // —— Ambient ——
  {
    id: 'ambient-piano-room',
    vibe: 'ambient',
    name: 'Piano Room',
    description: 'Dedicated piano lead/pad room (CPU soft-load)',
    bpm: 70,
    drumsBank: 'piano',
    tracks: [
      { name: 'Pulse', role: 'drums' },
      { name: 'Shimmer', role: 'hihats' },
      { name: 'Piano', role: 'pad' },
      { name: 'Lead', role: 'lead' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'major',
      melodicSounds: ['piano', 'sine'],
      fxBias: 'roomy',
    },
  },

  // —— Techno ——
  {
    id: 'techno-clean-breaks',
    vibe: 'techno',
    name: 'Clean Breaks',
    description: 'Clean break chops (dirt breaks fallback)',
    bpm: 165,
    drumsBank: 'clean-breaks',
    tracks: [
      { name: 'Break', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Chop', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Stab', role: 'lead' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'high',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
    },
  },
]
