import type { TrackRole } from './types'
import type { SoundChoice } from './kits-types'

export const DRUM_SOUND_CHOICES: Partial<Record<TrackRole, SoundChoice[]>> = {
  drums: [
    { id: '909', label: '909 punch', bank: 'RolandTR909' },
    { id: '909-alt', label: '909 alt hit', bank: 'RolandTR909', n: 1 },
    { id: '808', label: '808 boom', bank: 'RolandTR808' },
    { id: '808-alt', label: '808 alt hit', bank: 'RolandTR808', n: 1 },
    { id: '707', label: '707 sharp', bank: 'RolandTR707' },
    { id: '606', label: '606 tick', bank: 'RolandTR606' },
    { id: '505', label: '505 light', bank: 'RolandTR505' },
    { id: 'mpc60', label: 'MPC60', bank: 'AkaiMPC60' },
    { id: 'sp12', label: 'SP-12', bank: 'EmuSP12' },
    { id: 'linn', label: 'Linn crisp', bank: 'LinnDrum' },
    { id: 'lm1', label: 'LM-1', bank: 'LinnLM1' },
    { id: 'linn9000', label: 'Linn 9000', bank: 'Linn9000' },
    { id: 'dr110', label: 'DR-110', bank: 'BossDR110' },
    { id: 'dmx', label: 'DMX', bank: 'OberheimDMX' },
    { id: 'cr78', label: 'CR78 soft', bank: 'RolandCompurhythm78' },
    { id: 'cr1000', label: 'CR-1000', bank: 'RolandCompurhythm1000' },
    { id: 'cr8000', label: 'CR-8000', bank: 'RolandCompurhythm8000' },
    { id: 'lm2', label: 'LM-2', bank: 'LinnLM2' },
    { id: 'drumulator', label: 'Drumulator', bank: 'EmuDrumulator' },
    { id: 'drumtraks', label: 'DrumTraks', bank: 'SequentialCircuitsDrumtracks' },
    { id: 'r8', label: 'R-8', bank: 'RolandR8' },
    { id: 'sds5', label: 'SDS5', bank: 'SimmonsSDS5' },
    { id: 'dr550', label: 'DR-550', bank: 'BossDR550' },
    { id: 'dr220', label: 'DR-220', bank: 'BossDR220' },
    { id: 'sr16', label: 'SR-16', bank: 'AlesisSR16' },
    { id: 'hr16', label: 'HR-16', bank: 'AlesisHR16' },
    { id: '626', label: '626', bank: 'RolandTR626' },
    { id: 'xr10', label: 'XR-10', bank: 'AkaiXR10' },
    { id: 'rm50', label: 'RM-50', bank: 'YamahaRM50' },
    { id: 'ry30', label: 'RY-30', bank: 'YamahaRY30' },
    { id: 'rx5', label: 'RX-5', bank: 'YamahaRX5' },
    { id: 'rx21', label: 'RX-21', bank: 'YamahaRX21' },
    { id: 'mc303', label: 'MC-303', bank: 'RolandMC303' },
    { id: 'jd990', label: 'JD-990', bank: 'RolandJD990' },
    { id: 'mt32', label: 'MT-32', bank: 'RolandMT32' },
    { id: 'sys100', label: 'System 100', bank: 'RolandSystem100' },
    { id: 'm1', label: 'M1', bank: 'KorgM1' },
    { id: 'mfb512', label: 'MFB-512', bank: 'MFB512' },
    { id: 'dpm48', label: 'DPM-48', bank: 'SakataDPM48' },
    { id: 'spacedrum', label: 'Space Drum', bank: 'ViscoSpaceDrum' },
    { id: 'rz1', label: 'RZ-1', bank: 'CasioRZ1' },
    { id: 'sk1', label: 'SK-1', bank: 'CasioSK1' },
    { id: 'kr55', label: 'KR-55', bank: 'KorgKR55' },
    { id: 'rhythmac', label: 'RhythmAce', bank: 'RhythmAce' },
    { id: 'ms404', label: 'MS-404', bank: 'DoepferMS404' },
    { id: 'sctom', label: 'SC Tom', bank: 'SequentialCircuitsTom' },
  ],
  hihats: [
    { id: '909', label: '909 hats', bank: 'RolandTR909' },
    { id: '808', label: '808 hats', bank: 'RolandTR808' },
    { id: '707', label: '707 hats', bank: 'RolandTR707' },
    { id: '606', label: '606 hats', bank: 'RolandTR606' },
    { id: '505', label: '505 hats', bank: 'RolandTR505' },
    { id: 'mpc60', label: 'MPC60 hats', bank: 'AkaiMPC60' },
    { id: 'sp12', label: 'SP-12 hats', bank: 'EmuSP12' },
    { id: 'linn', label: 'Linn hats', bank: 'LinnDrum' },
    { id: 'lm1', label: 'LM-1 hats', bank: 'LinnLM1' },
    { id: 'linn9000', label: '9000 hats', bank: 'Linn9000' },
    { id: 'cr78', label: 'CR78 hats', bank: 'RolandCompurhythm78' },
    { id: 'cr1000', label: 'CR-1000 hats', bank: 'RolandCompurhythm1000' },
    { id: 'cr8000', label: 'CR-8000 hats', bank: 'RolandCompurhythm8000' },
    { id: 'lm2', label: 'LM-2 hats', bank: 'LinnLM2' },
    { id: 'drumulator', label: 'Drumulator hats', bank: 'EmuDrumulator' },
    { id: 'r8', label: 'R-8 hats', bank: 'RolandR8' },
    { id: 'sr16', label: 'SR-16 hats', bank: 'AlesisSR16' },
    { id: 'hr16', label: 'HR-16 hats', bank: 'AlesisHR16' },
    { id: '626', label: '626 hats', bank: 'RolandTR626' },
    { id: 'rm50', label: 'RM-50 hats', bank: 'YamahaRM50' },
    { id: 'ry30', label: 'RY-30 hats', bank: 'YamahaRY30' },
    { id: 'rx5', label: 'RX-5 hats', bank: 'YamahaRX5' },
    { id: 'mc303', label: 'MC-303 hats', bank: 'RolandMC303' },
    { id: 'jd990', label: 'JD-990 hats', bank: 'RolandJD990' },
    { id: 'dr550', label: 'DR-550 hats', bank: 'BossDR550' },
    { id: 'dr220', label: 'DR-220 hats', bank: 'BossDR220' },
    { id: 'm1', label: 'M1 hats', bank: 'KorgM1' },
    { id: 'sys100', label: 'Sys100 hats', bank: 'RolandSystem100' },
    { id: 'rz1', label: 'RZ-1 hats', bank: 'CasioRZ1' },
    { id: 'sk1', label: 'SK-1 hats', bank: 'CasioSK1' },
    { id: 'kr55', label: 'KR-55 hats', bank: 'KorgKR55' },
    { id: 'rhythmac', label: 'RhythmAce hats', bank: 'RhythmAce' },
    { id: 'ms404', label: 'MS-404 hats', bank: 'DoepferMS404' },
  ],
  fx: [
    { id: '909', label: '909 clap', bank: 'RolandTR909' },
    { id: '808', label: '808 clap', bank: 'RolandTR808' },
    { id: '707', label: '707 clap', bank: 'RolandTR707' },
    { id: '505', label: '505 clap', bank: 'RolandTR505' },
    { id: 'mpc60', label: 'MPC60 snare', bank: 'AkaiMPC60' },
    { id: 'sp12', label: 'SP-12 rim', bank: 'EmuSP12' },
    { id: '727', label: '727 perc', bank: 'RolandTR727' },
    { id: 'linn', label: 'Linn snare', bank: 'LinnDrum' },
    { id: 'linn9000', label: '9000 snare', bank: 'Linn9000' },
    { id: 'dmx', label: 'DMX clap', bank: 'OberheimDMX' },
    { id: 'cr78', label: 'CR78 perc', bank: 'RolandCompurhythm78' },
    { id: 'cr1000', label: 'CR-1000 clap', bank: 'RolandCompurhythm1000' },
    { id: 'cr8000', label: 'CR-8000 clap', bank: 'RolandCompurhythm8000' },
    { id: 'lm2', label: 'LM-2 clap', bank: 'LinnLM2' },
    { id: 'drumulator', label: 'Drumulator clap', bank: 'EmuDrumulator' },
    { id: 'r8', label: 'R-8 clap', bank: 'RolandR8' },
    { id: 'sr16', label: 'SR-16 snare', bank: 'AlesisSR16' },
    { id: 'hr16', label: 'HR-16 snare', bank: 'AlesisHR16' },
    { id: '626', label: '626 clap', bank: 'RolandTR626' },
    { id: 'rm50', label: 'RM-50 clap', bank: 'YamahaRM50' },
    { id: 'ry30', label: 'RY-30 clap', bank: 'YamahaRY30' },
    { id: 'rx5', label: 'RX-5 rim', bank: 'YamahaRX5' },
    { id: 'rx21', label: 'RX-21 clap', bank: 'YamahaRX21' },
    { id: 'mc303', label: 'MC-303 clap', bank: 'RolandMC303' },
    { id: 'jd990', label: 'JD-990 clap', bank: 'RolandJD990' },
    { id: 'mt32', label: 'MT-32 snare', bank: 'RolandMT32' },
    { id: 'sds5', label: 'SDS5 snare', bank: 'SimmonsSDS5' },
    { id: 'mfb512', label: 'MFB-512 clap', bank: 'MFB512' },
    { id: 'sys100', label: 'Sys100 snare', bank: 'RolandSystem100' },
    { id: 'rz1', label: 'RZ-1 clap', bank: 'CasioRZ1' },
    { id: 'sk1', label: 'SK-1 snare', bank: 'CasioSK1' },
    { id: 'kr55', label: 'KR-55 rim', bank: 'KorgKR55' },
    { id: 'rhythmac', label: 'RhythmAce snare', bank: 'RhythmAce' },
    { id: 'ms404', label: 'MS-404 snare', bank: 'DoepferMS404' },
    { id: 'sctom', label: 'SC Tom', bank: 'SequentialCircuitsTom' },
  ]
}
