import type { TrackRole } from './types'
import type { SoundChoice } from './kits-types'

/**
 * Pitched VCSL / wavetables that actually play as melodic voices.
 * Soft/stacc/vib clones omitted. Useful orphans only (bowed vibes, spiccato, didgeridoo).
 * FX-flavored WTs (crickets/curses/bad_day/echoes) live on the FX sheet — not here.
 */
export const HIDDEN_PITCHED_CHOICES: SoundChoice[] = [
  { id: 'vibraphone', label: 'Vibraphone', sound: 'vibraphone' },
  { id: 'vibraphone-bowed', label: 'Vibraphone bowed', sound: 'vibraphone_bowed' },
  { id: 'harmonica', label: 'Harmonica', sound: 'harmonica' },
  { id: 'balafon', label: 'Balafon', sound: 'balafon_hard' },
  { id: 'xylophone', label: 'Xylophone', sound: 'xylophone_hard_ff' },
  { id: 'glockenspiel', label: 'Glockenspiel', sound: 'glockenspiel' },
  { id: 'harp', label: 'Harp', sound: 'harp' },
  { id: 'folkharp', label: 'Folk harp', sound: 'folkharp' },
  { id: 'psaltery', label: 'Psaltery', sound: 'psaltery_pluck' },
  { id: 'psaltery-bow', label: 'Psaltery bow', sound: 'psaltery_bow' },
  { id: 'psaltery-spiccato', label: 'Psaltery spiccato', sound: 'psaltery_spiccato' },
  { id: 'dantranh', label: 'Dan tranh', sound: 'dantranh' },
  { id: 'clavisynth', label: 'Clavisynth', sound: 'clavisynth' },
  { id: 'fmpiano', label: 'FM piano', sound: 'fmpiano' },
  { id: 'piano1', label: 'Piano 1', sound: 'piano1' },
  { id: 'kawai', label: 'Kawai', sound: 'kawai' },
  { id: 'steinway', label: 'Steinway', sound: 'steinway' },
  { id: 'kalimba2', label: 'Kalimba 2', sound: 'kalimba2' },
  { id: 'kalimba3', label: 'Kalimba 3', sound: 'kalimba3' },
  { id: 'kalimba4', label: 'Kalimba 4', sound: 'kalimba4' },
  { id: 'kalimba5', label: 'Kalimba 5', sound: 'kalimba5' },
  { id: 'organ-4inch', label: 'Organ 4 inch', sound: 'organ_4inch' },
  { id: 'ocarina', label: 'Ocarina', sound: 'ocarina' },
  { id: 'ocarina-small', label: 'Ocarina small', sound: 'ocarina_small' },
  { id: 'recorder-alto', label: 'Recorder alto', sound: 'recorder_alto_sus' },
  { id: 'recorder-bass', label: 'Recorder bass', sound: 'recorder_bass_sus' },
  { id: 'recorder-soprano', label: 'Recorder soprano', sound: 'recorder_soprano_sus' },
  { id: 'recorder-tenor', label: 'Recorder tenor', sound: 'recorder_tenor_sus' },
  { id: 'saxello', label: 'Saxello', sound: 'saxello' },
  { id: 'didgeridoo', label: 'Didgeridoo', sound: 'didgeridoo' },
  { id: 'strumstick', label: 'Strumstick', sound: 'strumstick' },
  { id: 'super64', label: 'Super 64', sound: 'super64' },
  { id: 'tubularbells', label: 'Tubular bells', sound: 'tubularbells' },
  { id: 'tubularbells2', label: 'Tubular bells 2', sound: 'tubularbells2' },
  { id: 'wineglass', label: 'Wineglass', sound: 'wineglass_slow' },
  { id: 'wt-basique', label: 'WT basique', sound: 'wt_digital_basique' },
]

/** FX-flavored wavetables — one-shot / texture, not melodic Shuffle citizens. */
export const WT_FX_CHOICES: SoundChoice[] = [
  { id: 'wt-bad-day', label: 'WT bad day', sound: 'wt_digital_bad_day' },
  { id: 'wt-crickets', label: 'WT crickets', sound: 'wt_digital_crickets' },
  { id: 'wt-curses', label: 'WT curses', sound: 'wt_digital_curses' },
  { id: 'wt-echoes', label: 'WT echoes', sound: 'wt_digital_echoes' },
]

/** Useful Dirt melodic orphans (instruments / pitched synths — not FX one-shots). */
export const DIRT_MELODIC_ORPHANS: SoundChoice[] = [
  { id: 'dirt-sitar', label: 'Dirt sitar', sound: 'sitar' },
  { id: 'dirt-fm', label: 'Dirt FM', sound: 'fm' },
  { id: 'dirt-sid', label: 'Dirt SID', sound: 'sid' },
]

/** GM novelty excluded from catalog entirely (not even FX). */
export const GM_EXCLUDED_NOVELTY = [
  'gm_gunshot', 'gm_helicopter', 'gm_seashore', 'gm_bird_tweet', 'gm_telephone',
  'gm_applause', 'gm_breath_noise', 'gm_reverse_cymbal', 'gm_woodblock', 'gm_taiko_drum',
  'gm_melodic_tom', 'gm_synth_drum', 'gm_agogo', 'gm_tinkle_bell', 'gm_guitar_fret_noise',
] as const

/** GM percussion / FX buses — FX sheet only (never melodic Shuffle pools). */
export const GM_FX_CHOICES: SoundChoice[] = [
  { id: 'gm-orchestra-hit', label: 'GM Orchestra hit', sound: 'gm_orchestra_hit' },
  { id: 'gm-timpani', label: 'GM Timpani', sound: 'gm_timpani' },
  { id: 'gm-steel-drums', label: 'GM Steel drums', sound: 'gm_steel_drums' },
  { id: 'gm-fx-rain', label: 'GM FX rain', sound: 'gm_fx_rain' },
  { id: 'gm-fx-soundtrack', label: 'GM FX soundtrack', sound: 'gm_fx_soundtrack' },
  { id: 'gm-fx-crystal', label: 'GM FX crystal', sound: 'gm_fx_crystal' },
  { id: 'gm-fx-atmosphere', label: 'GM FX atmosphere', sound: 'gm_fx_atmosphere' },
  { id: 'gm-fx-brightness', label: 'GM FX brightness', sound: 'gm_fx_brightness' },
  { id: 'gm-fx-goblins', label: 'GM FX goblins', sound: 'gm_fx_goblins' },
  { id: 'gm-fx-echoes', label: 'GM FX echoes', sound: 'gm_fx_echoes' },
  { id: 'gm-fx-sci-fi', label: 'GM FX sci-fi', sound: 'gm_fx_sci_fi' },
]

/** Role catalogs grouped by type for a scannable Sound sheet. */
export const MELODIC_SOUND_CHOICES: Partial<Record<TrackRole, SoundChoice[]>> = {
  bass: [
    // Synths
    { id: 'saw', label: 'Saw bass', sound: 'sawtooth' },
    { id: 'square', label: 'Square bass', sound: 'square' },
    { id: 'sine', label: 'Sine sub', sound: 'sine' },
    { id: 'tri', label: 'Triangle', sound: 'triangle' },
    // Keys
    { id: 'piano-bass', label: 'Piano bass', sound: 'piano' },
    // Dirt bass
    { id: 'bass', label: 'Dirt bass', sound: 'bass' },
    { id: 'jvbass', label: 'JV bass', sound: 'jvbass' },
    { id: 'wobble', label: 'Wobble', sound: 'wobble' },
    { id: 'jungbass', label: 'Jungle bass', sound: 'jungbass' },
    // GM bass / low strings
    { id: 'gm-acoustic-bass', label: 'GM Acoustic bass', sound: 'gm_acoustic_bass' },
    { id: 'gm-electric-bass-finger', label: 'GM Finger bass', sound: 'gm_electric_bass_finger' },
    { id: 'gm-electric-bass-pick', label: 'GM Pick bass', sound: 'gm_electric_bass_pick' },
    { id: 'gm-fretless-bass', label: 'GM Fretless bass', sound: 'gm_fretless_bass' },
    { id: 'gm-slap-bass-1', label: 'GM Slap bass 1', sound: 'gm_slap_bass_1' },
    { id: 'gm-slap-bass-2', label: 'GM Slap bass 2', sound: 'gm_slap_bass_2' },
    { id: 'gm-synth-bass-1', label: 'GM Synth bass 1', sound: 'gm_synth_bass_1' },
    { id: 'gm-synth-bass-2', label: 'GM Synth bass 2', sound: 'gm_synth_bass_2' },
    { id: 'gm-cello', label: 'Cello', sound: 'gm_cello' },
    { id: 'gm-contrabass', label: 'GM Contrabass', sound: 'gm_contrabass' },
    { id: 'gm-tuba', label: 'GM Tuba', sound: 'gm_tuba' },
    { id: 'gm-bassoon', label: 'GM Bassoon', sound: 'gm_bassoon' },
    { id: 'gm-lead-8-bass-lead', label: 'GM Bass lead', sound: 'gm_lead_8_bass_lead' },
    // VCSL drone / low
    { id: 'didgeridoo-bass', label: 'Didgeridoo', sound: 'didgeridoo' },
    { id: 'recorder-bass-b', label: 'Recorder bass', sound: 'recorder_bass_sus' },
  ],
  lead: [
    // Synths
    { id: 'square', label: 'Square lead', sound: 'square' },
    { id: 'saw', label: 'Saw lead', sound: 'sawtooth' },
    { id: 'tri', label: 'Soft tri', sound: 'triangle' },
    { id: 'sine', label: 'Sine lead', sound: 'sine' },
    // Keys / mallets
    { id: 'piano', label: 'Piano lead', sound: 'piano' },
    { id: 'marimba', label: 'Marimba', sound: 'marimba' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    // Organs
    { id: 'pipeorgan-loud', label: 'Pipe organ', sound: 'pipeorgan_loud' },
    { id: 'organ-8inch', label: 'Organ 8 inch', sound: 'organ_8inch' },
    { id: 'organ-full', label: 'Organ full', sound: 'organ_full' },
    { id: 'pipeorgan-quiet', label: 'Pipe organ quiet', sound: 'pipeorgan_quiet' },
    // Wavetables
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
    { id: 'wt-vgame', label: 'WT vgame', sound: 'wt_vgame' },
    // Dirt melodic
    { id: 'sax', label: 'Sax', sound: 'sax' },
    { id: 'gtr', label: 'Guitar', sound: 'gtr' },
    { id: 'arpy', label: 'Arpy', sound: 'arpy' },
    { id: 'dirt-sitar', label: 'Dirt sitar', sound: 'sitar' },
    { id: 'dirt-fm', label: 'Dirt FM', sound: 'fm' },
    { id: 'dirt-sid', label: 'Dirt SID', sound: 'sid' },
    // GM keys
    { id: 'gm-piano', label: 'GM Piano', sound: 'gm_piano' },
    { id: 'gm-epiano1', label: 'GM E-piano 1', sound: 'gm_epiano1' },
    { id: 'gm-epiano2', label: 'GM E-piano 2', sound: 'gm_epiano2' },
    { id: 'gm-harpsichord', label: 'GM Harpsichord', sound: 'gm_harpsichord' },
    { id: 'gm-clavinet', label: 'GM Clavinet', sound: 'gm_clavinet' },
    { id: 'gm-celesta', label: 'GM Celesta', sound: 'gm_celesta' },
    { id: 'gm-glockenspiel', label: 'GM Glockenspiel', sound: 'gm_glockenspiel' },
    { id: 'gm-music-box', label: 'GM Music box', sound: 'gm_music_box' },
    { id: 'gm-vibraphone', label: 'GM Vibraphone', sound: 'gm_vibraphone' },
    { id: 'gm-marimba', label: 'GM Marimba', sound: 'gm_marimba' },
    { id: 'gm-xylophone', label: 'GM Xylophone', sound: 'gm_xylophone' },
    { id: 'gm-tubular-bells', label: 'GM Tubular bells', sound: 'gm_tubular_bells' },
    { id: 'gm-dulcimer', label: 'GM Dulcimer', sound: 'gm_dulcimer' },
    // GM guitars
    { id: 'gm-acoustic-guitar-nylon', label: 'GM Nylon guitar', sound: 'gm_acoustic_guitar_nylon' },
    { id: 'gm-acoustic-guitar-steel', label: 'GM Steel guitar', sound: 'gm_acoustic_guitar_steel' },
    { id: 'gm-electric-guitar-jazz', label: 'GM Jazz guitar', sound: 'gm_electric_guitar_jazz' },
    { id: 'gm-electric-guitar-clean', label: 'GM Clean guitar', sound: 'gm_electric_guitar_clean' },
    { id: 'gm-electric-guitar-muted', label: 'GM Muted guitar', sound: 'gm_electric_guitar_muted' },
    { id: 'gm-overdriven-guitar', label: 'GM Overdrive guitar', sound: 'gm_overdriven_guitar' },
    { id: 'gm-distortion-guitar', label: 'GM Distortion guitar', sound: 'gm_distortion_guitar' },
    { id: 'gm-guitar-harmonics', label: 'GM Guitar harmonics', sound: 'gm_guitar_harmonics' },
    // GM strings
    { id: 'gm-violin', label: 'Violin', sound: 'gm_violin' },
    { id: 'gm-viola', label: 'GM Viola', sound: 'gm_viola' },
    { id: 'gm-cello', label: 'Cello', sound: 'gm_cello' },
    { id: 'gm-fiddle', label: 'GM Fiddle', sound: 'gm_fiddle' },
    { id: 'gm-pizzicato-strings', label: 'GM Pizzicato', sound: 'gm_pizzicato_strings' },
    { id: 'gm-orchestral-harp', label: 'GM Orchestral harp', sound: 'gm_orchestral_harp' },
    // GM brass
    { id: 'gm-trumpet', label: 'GM Trumpet', sound: 'gm_trumpet' },
    { id: 'gm-trombone', label: 'GM Trombone', sound: 'gm_trombone' },
    { id: 'gm-muted-trumpet', label: 'GM Muted trumpet', sound: 'gm_muted_trumpet' },
    { id: 'gm-french-horn', label: 'GM French horn', sound: 'gm_french_horn' },
    { id: 'gm-brass-section', label: 'GM Brass section', sound: 'gm_brass_section' },
    { id: 'gm-synth-brass-1', label: 'GM Synth brass 1', sound: 'gm_synth_brass_1' },
    { id: 'gm-synth-brass-2', label: 'GM Synth brass 2', sound: 'gm_synth_brass_2' },
    // GM winds
    { id: 'gm-soprano-sax', label: 'GM Soprano sax', sound: 'gm_soprano_sax' },
    { id: 'gm-alto-sax', label: 'GM Alto sax', sound: 'gm_alto_sax' },
    { id: 'gm-tenor-sax', label: 'GM Tenor sax', sound: 'gm_tenor_sax' },
    { id: 'gm-baritone-sax', label: 'GM Baritone sax', sound: 'gm_baritone_sax' },
    { id: 'gm-oboe', label: 'GM Oboe', sound: 'gm_oboe' },
    { id: 'gm-english-horn', label: 'GM English horn', sound: 'gm_english_horn' },
    { id: 'gm-clarinet', label: 'GM Clarinet', sound: 'gm_clarinet' },
    { id: 'gm-piccolo', label: 'GM Piccolo', sound: 'gm_piccolo' },
    { id: 'gm-flute', label: 'GM Flute', sound: 'gm_flute' },
    { id: 'gm-recorder', label: 'GM Recorder', sound: 'gm_recorder' },
    { id: 'gm-pan-flute', label: 'GM Pan flute', sound: 'gm_pan_flute' },
    { id: 'gm-blown-bottle', label: 'GM Blown bottle', sound: 'gm_blown_bottle' },
    { id: 'gm-shakuhachi', label: 'GM Shakuhachi', sound: 'gm_shakuhachi' },
    { id: 'gm-whistle', label: 'GM Whistle', sound: 'gm_whistle' },
    { id: 'gm-ocarina', label: 'GM Ocarina', sound: 'gm_ocarina' },
    // GM synth leads
    { id: 'gm-lead-1-square', label: 'GM Lead square', sound: 'gm_lead_1_square' },
    { id: 'gm-lead-2-sawtooth', label: 'GM Lead saw', sound: 'gm_lead_2_sawtooth' },
    { id: 'gm-lead-3-calliope', label: 'GM Lead calliope', sound: 'gm_lead_3_calliope' },
    { id: 'gm-lead-4-chiff', label: 'GM Lead chiff', sound: 'gm_lead_4_chiff' },
    { id: 'gm-lead-5-charang', label: 'GM Lead charang', sound: 'gm_lead_5_charang' },
    { id: 'gm-lead-6-voice', label: 'GM Lead voice', sound: 'gm_lead_6_voice' },
    { id: 'gm-lead-7-fifths', label: 'GM Lead fifths', sound: 'gm_lead_7_fifths' },
    // GM world
    { id: 'gm-sitar', label: 'GM Sitar', sound: 'gm_sitar' },
    { id: 'gm-banjo', label: 'GM Banjo', sound: 'gm_banjo' },
    { id: 'gm-shamisen', label: 'GM Shamisen', sound: 'gm_shamisen' },
    { id: 'gm-koto', label: 'GM Koto', sound: 'gm_koto' },
    { id: 'gm-kalimba', label: 'GM Kalimba', sound: 'gm_kalimba' },
    { id: 'gm-bagpipe', label: 'GM Bagpipe', sound: 'gm_bagpipe' },
    { id: 'gm-shanai', label: 'GM Shanai', sound: 'gm_shanai' },
    { id: 'gm-harmonica', label: 'GM Harmonica', sound: 'gm_harmonica' },
    { id: 'gm-accordion', label: 'GM Accordion', sound: 'gm_accordion' },
    // VCSL / WT pitched
    ...HIDDEN_PITCHED_CHOICES,
  ],
  pad: [
    // Synths
    { id: 'sine', label: 'Sine pad', sound: 'sine' },
    { id: 'tri', label: 'Tri pad', sound: 'triangle' },
    { id: 'saw', label: 'Saw pad', sound: 'sawtooth' },
    { id: 'square', label: 'Square pad', sound: 'square' },
    // Keys
    { id: 'piano', label: 'Piano room', sound: 'piano' },
    // Organs / wash
    { id: 'organ-wash', label: 'Organ wash', sound: 'organ_8inch' },
    { id: 'pipeorgan', label: 'Pipe organ', sound: 'pipeorgan_loud' },
    { id: 'pipeorgan-quiet-pad', label: 'Pipe organ quiet', sound: 'pipeorgan_quiet' },
    { id: 'vcsl-organ', label: 'VCSL organ', sound: 'organ_full' },
    // Soft mallet
    { id: 'marimba-pad', label: 'Marimba pad', sound: 'marimba' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    // Wavetables
    { id: 'wt-vgame', label: 'WT pad', sound: 'wt_vgame' },
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
    // GM pads
    { id: 'gm-pad-new-age', label: 'GM Pad new age', sound: 'gm_pad_new_age' },
    { id: 'gm-pad-warm', label: 'GM Pad warm', sound: 'gm_pad_warm' },
    { id: 'gm-pad-poly', label: 'GM Pad poly', sound: 'gm_pad_poly' },
    { id: 'gm-pad-choir', label: 'GM Pad choir', sound: 'gm_pad_choir' },
    { id: 'gm-pad-bowed', label: 'GM Pad bowed', sound: 'gm_pad_bowed' },
    { id: 'gm-pad-metallic', label: 'GM Pad metallic', sound: 'gm_pad_metallic' },
    { id: 'gm-pad-halo', label: 'GM Pad halo', sound: 'gm_pad_halo' },
    { id: 'gm-pad-sweep', label: 'GM Pad sweep', sound: 'gm_pad_sweep' },
    // GM choir
    { id: 'gm-choir-aahs', label: 'GM Choir aahs', sound: 'gm_choir_aahs' },
    { id: 'gm-voice-oohs', label: 'GM Voice oohs', sound: 'gm_voice_oohs' },
    { id: 'gm-synth-choir', label: 'GM Synth choir', sound: 'gm_synth_choir' },
    // GM string ensembles
    { id: 'gm-string-ensemble-1', label: 'String ensemble', sound: 'gm_string_ensemble_1' },
    { id: 'gm-string-ensemble-2', label: 'GM String ensemble 2', sound: 'gm_string_ensemble_2' },
    { id: 'gm-synth-strings-1', label: 'GM Synth strings 1', sound: 'gm_synth_strings_1' },
    { id: 'gm-synth-strings-2', label: 'GM Synth strings 2', sound: 'gm_synth_strings_2' },
    { id: 'gm-tremolo-strings', label: 'GM Tremolo strings', sound: 'gm_tremolo_strings' },
    // GM organs
    { id: 'gm-drawbar-organ', label: 'GM Drawbar organ', sound: 'gm_drawbar_organ' },
    { id: 'gm-percussive-organ', label: 'GM Perc organ', sound: 'gm_percussive_organ' },
    { id: 'gm-rock-organ', label: 'GM Rock organ', sound: 'gm_rock_organ' },
    { id: 'gm-church-organ', label: 'GM Church organ', sound: 'gm_church_organ' },
    { id: 'gm-reed-organ', label: 'GM Reed organ', sound: 'gm_reed_organ' },
    { id: 'gm-accordion', label: 'GM Accordion', sound: 'gm_accordion' },
    { id: 'gm-harmonica', label: 'GM Harmonica', sound: 'gm_harmonica' },
    { id: 'gm-bandoneon', label: 'GM Bandoneon', sound: 'gm_bandoneon' },
    // VCSL / WT pitched
    ...HIDDEN_PITCHED_CHOICES,
  ],
  arp: [
    // Synths
    { id: 'tri', label: 'Tri arp', sound: 'triangle' },
    { id: 'sine', label: 'Sine arp', sound: 'sine' },
    { id: 'square', label: 'Square arp', sound: 'square' },
    { id: 'saw', label: 'Saw arp', sound: 'sawtooth' },
    // Keys / pluck
    { id: 'piano', label: 'Piano arp', sound: 'piano' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    { id: 'marimba', label: 'Marimba', sound: 'marimba' },
    { id: 'arpy', label: 'Arpy', sound: 'arpy' },
    // Wavetables
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
    // Dirt pitched
    { id: 'dirt-fm-arp', label: 'Dirt FM', sound: 'fm' },
    { id: 'dirt-sid-arp', label: 'Dirt SID', sound: 'sid' },
    { id: 'dirt-sitar-arp', label: 'Dirt sitar', sound: 'sitar' },
    // GM plucky
    { id: 'gm-pizzicato-strings', label: 'GM Pizzicato', sound: 'gm_pizzicato_strings' },
    { id: 'gm-music-box', label: 'GM Music box', sound: 'gm_music_box' },
    { id: 'gm-celesta', label: 'GM Celesta', sound: 'gm_celesta' },
    { id: 'gm-kalimba', label: 'GM Kalimba', sound: 'gm_kalimba' },
    { id: 'gm-acoustic-guitar-nylon', label: 'GM Nylon guitar', sound: 'gm_acoustic_guitar_nylon' },
    { id: 'gm-orchestral-harp', label: 'GM Orchestral harp', sound: 'gm_orchestral_harp' },
    { id: 'gm-dulcimer', label: 'GM Dulcimer', sound: 'gm_dulcimer' },
    { id: 'gm-glockenspiel', label: 'GM Glockenspiel', sound: 'gm_glockenspiel' },
    { id: 'gm-marimba', label: 'GM Marimba', sound: 'gm_marimba' },
    { id: 'gm-xylophone', label: 'GM Xylophone', sound: 'gm_xylophone' },
    { id: 'gm-vibraphone', label: 'GM Vibraphone', sound: 'gm_vibraphone' },
    { id: 'gm-tubular-bells', label: 'GM Tubular bells', sound: 'gm_tubular_bells' },
    { id: 'gm-banjo', label: 'GM Banjo', sound: 'gm_banjo' },
    { id: 'gm-koto', label: 'GM Koto', sound: 'gm_koto' },
    { id: 'gm-clavinet', label: 'GM Clavinet', sound: 'gm_clavinet' },
    { id: 'gm-harpsichord', label: 'GM Harpsichord', sound: 'gm_harpsichord' },
    { id: 'gm-epiano1', label: 'GM E-piano 1', sound: 'gm_epiano1' },
    { id: 'gm-piano', label: 'GM Piano', sound: 'gm_piano' },
    // VCSL / WT pitched
    ...HIDDEN_PITCHED_CHOICES,
  ],
  vox: [
    { id: 'hmm', label: 'Hmm', sound: 'hmm' },
    { id: 'speechless', label: 'Speech', sound: 'speechless' },
    { id: 'breath', label: 'Breath', sound: 'breath' },
    { id: 'diphone', label: 'Diphone', sound: 'diphone' },
  ],
  custom: [
    // Synths / keys / organs / WT
    { id: 'saw', label: 'Saw', sound: 'sawtooth' },
    { id: 'sine', label: 'Sine', sound: 'sine' },
    { id: 'piano', label: 'Piano', sound: 'piano' },
    { id: 'kalimba', label: 'Kalimba', sound: 'kalimba' },
    { id: 'marimba', label: 'Marimba', sound: 'marimba' },
    { id: 'organ-8inch', label: 'Organ 8 inch', sound: 'organ_8inch' },
    { id: 'wt-digital', label: 'WT digital', sound: 'wt_digital' },
    { id: 'wt-vgame', label: 'WT vgame', sound: 'wt_vgame' },
    { id: 'dirt-sitar', label: 'Dirt sitar', sound: 'sitar' },
    { id: 'dirt-fm', label: 'Dirt FM', sound: 'fm' },
    { id: 'dirt-sid', label: 'Dirt SID', sound: 'sid' },
    // GM (keys → guitars → strings → brass → winds → leads → pads → choir → organs → world → bass)
    { id: 'gm-piano', label: 'GM Piano', sound: 'gm_piano' },
    { id: 'gm-epiano1', label: 'GM E-piano 1', sound: 'gm_epiano1' },
    { id: 'gm-epiano2', label: 'GM E-piano 2', sound: 'gm_epiano2' },
    { id: 'gm-harpsichord', label: 'GM Harpsichord', sound: 'gm_harpsichord' },
    { id: 'gm-clavinet', label: 'GM Clavinet', sound: 'gm_clavinet' },
    { id: 'gm-celesta', label: 'GM Celesta', sound: 'gm_celesta' },
    { id: 'gm-glockenspiel', label: 'GM Glockenspiel', sound: 'gm_glockenspiel' },
    { id: 'gm-music-box', label: 'GM Music box', sound: 'gm_music_box' },
    { id: 'gm-vibraphone', label: 'GM Vibraphone', sound: 'gm_vibraphone' },
    { id: 'gm-marimba', label: 'GM Marimba', sound: 'gm_marimba' },
    { id: 'gm-xylophone', label: 'GM Xylophone', sound: 'gm_xylophone' },
    { id: 'gm-tubular-bells', label: 'GM Tubular bells', sound: 'gm_tubular_bells' },
    { id: 'gm-dulcimer', label: 'GM Dulcimer', sound: 'gm_dulcimer' },
    { id: 'gm-acoustic-guitar-nylon', label: 'GM Nylon guitar', sound: 'gm_acoustic_guitar_nylon' },
    { id: 'gm-acoustic-guitar-steel', label: 'GM Steel guitar', sound: 'gm_acoustic_guitar_steel' },
    { id: 'gm-electric-guitar-jazz', label: 'GM Jazz guitar', sound: 'gm_electric_guitar_jazz' },
    { id: 'gm-electric-guitar-clean', label: 'GM Clean guitar', sound: 'gm_electric_guitar_clean' },
    { id: 'gm-electric-guitar-muted', label: 'GM Muted guitar', sound: 'gm_electric_guitar_muted' },
    { id: 'gm-overdriven-guitar', label: 'GM Overdrive guitar', sound: 'gm_overdriven_guitar' },
    { id: 'gm-distortion-guitar', label: 'GM Distortion guitar', sound: 'gm_distortion_guitar' },
    { id: 'gm-guitar-harmonics', label: 'GM Guitar harmonics', sound: 'gm_guitar_harmonics' },
    { id: 'gm-violin', label: 'Violin', sound: 'gm_violin' },
    { id: 'gm-viola', label: 'GM Viola', sound: 'gm_viola' },
    { id: 'gm-cello', label: 'Cello', sound: 'gm_cello' },
    { id: 'gm-fiddle', label: 'GM Fiddle', sound: 'gm_fiddle' },
    { id: 'gm-pizzicato-strings', label: 'GM Pizzicato', sound: 'gm_pizzicato_strings' },
    { id: 'gm-orchestral-harp', label: 'GM Orchestral harp', sound: 'gm_orchestral_harp' },
    { id: 'gm-string-ensemble-1', label: 'String ensemble', sound: 'gm_string_ensemble_1' },
    { id: 'gm-string-ensemble-2', label: 'GM String ensemble 2', sound: 'gm_string_ensemble_2' },
    { id: 'gm-synth-strings-1', label: 'GM Synth strings 1', sound: 'gm_synth_strings_1' },
    { id: 'gm-synth-strings-2', label: 'GM Synth strings 2', sound: 'gm_synth_strings_2' },
    { id: 'gm-tremolo-strings', label: 'GM Tremolo strings', sound: 'gm_tremolo_strings' },
    { id: 'gm-trumpet', label: 'GM Trumpet', sound: 'gm_trumpet' },
    { id: 'gm-trombone', label: 'GM Trombone', sound: 'gm_trombone' },
    { id: 'gm-muted-trumpet', label: 'GM Muted trumpet', sound: 'gm_muted_trumpet' },
    { id: 'gm-french-horn', label: 'GM French horn', sound: 'gm_french_horn' },
    { id: 'gm-brass-section', label: 'GM Brass section', sound: 'gm_brass_section' },
    { id: 'gm-synth-brass-1', label: 'GM Synth brass 1', sound: 'gm_synth_brass_1' },
    { id: 'gm-synth-brass-2', label: 'GM Synth brass 2', sound: 'gm_synth_brass_2' },
    { id: 'gm-soprano-sax', label: 'GM Soprano sax', sound: 'gm_soprano_sax' },
    { id: 'gm-alto-sax', label: 'GM Alto sax', sound: 'gm_alto_sax' },
    { id: 'gm-tenor-sax', label: 'GM Tenor sax', sound: 'gm_tenor_sax' },
    { id: 'gm-baritone-sax', label: 'GM Baritone sax', sound: 'gm_baritone_sax' },
    { id: 'gm-oboe', label: 'GM Oboe', sound: 'gm_oboe' },
    { id: 'gm-english-horn', label: 'GM English horn', sound: 'gm_english_horn' },
    { id: 'gm-clarinet', label: 'GM Clarinet', sound: 'gm_clarinet' },
    { id: 'gm-piccolo', label: 'GM Piccolo', sound: 'gm_piccolo' },
    { id: 'gm-flute', label: 'GM Flute', sound: 'gm_flute' },
    { id: 'gm-recorder', label: 'GM Recorder', sound: 'gm_recorder' },
    { id: 'gm-pan-flute', label: 'GM Pan flute', sound: 'gm_pan_flute' },
    { id: 'gm-blown-bottle', label: 'GM Blown bottle', sound: 'gm_blown_bottle' },
    { id: 'gm-shakuhachi', label: 'GM Shakuhachi', sound: 'gm_shakuhachi' },
    { id: 'gm-whistle', label: 'GM Whistle', sound: 'gm_whistle' },
    { id: 'gm-ocarina', label: 'GM Ocarina', sound: 'gm_ocarina' },
    { id: 'gm-lead-1-square', label: 'GM Lead square', sound: 'gm_lead_1_square' },
    { id: 'gm-lead-2-sawtooth', label: 'GM Lead saw', sound: 'gm_lead_2_sawtooth' },
    { id: 'gm-lead-3-calliope', label: 'GM Lead calliope', sound: 'gm_lead_3_calliope' },
    { id: 'gm-lead-4-chiff', label: 'GM Lead chiff', sound: 'gm_lead_4_chiff' },
    { id: 'gm-lead-5-charang', label: 'GM Lead charang', sound: 'gm_lead_5_charang' },
    { id: 'gm-lead-6-voice', label: 'GM Lead voice', sound: 'gm_lead_6_voice' },
    { id: 'gm-lead-7-fifths', label: 'GM Lead fifths', sound: 'gm_lead_7_fifths' },
    { id: 'gm-pad-new-age', label: 'GM Pad new age', sound: 'gm_pad_new_age' },
    { id: 'gm-pad-warm', label: 'GM Pad warm', sound: 'gm_pad_warm' },
    { id: 'gm-pad-poly', label: 'GM Pad poly', sound: 'gm_pad_poly' },
    { id: 'gm-pad-choir', label: 'GM Pad choir', sound: 'gm_pad_choir' },
    { id: 'gm-pad-bowed', label: 'GM Pad bowed', sound: 'gm_pad_bowed' },
    { id: 'gm-pad-metallic', label: 'GM Pad metallic', sound: 'gm_pad_metallic' },
    { id: 'gm-pad-halo', label: 'GM Pad halo', sound: 'gm_pad_halo' },
    { id: 'gm-pad-sweep', label: 'GM Pad sweep', sound: 'gm_pad_sweep' },
    { id: 'gm-choir-aahs', label: 'GM Choir aahs', sound: 'gm_choir_aahs' },
    { id: 'gm-voice-oohs', label: 'GM Voice oohs', sound: 'gm_voice_oohs' },
    { id: 'gm-synth-choir', label: 'GM Synth choir', sound: 'gm_synth_choir' },
    { id: 'gm-drawbar-organ', label: 'GM Drawbar organ', sound: 'gm_drawbar_organ' },
    { id: 'gm-percussive-organ', label: 'GM Perc organ', sound: 'gm_percussive_organ' },
    { id: 'gm-rock-organ', label: 'GM Rock organ', sound: 'gm_rock_organ' },
    { id: 'gm-church-organ', label: 'GM Church organ', sound: 'gm_church_organ' },
    { id: 'gm-reed-organ', label: 'GM Reed organ', sound: 'gm_reed_organ' },
    { id: 'gm-accordion', label: 'GM Accordion', sound: 'gm_accordion' },
    { id: 'gm-harmonica', label: 'GM Harmonica', sound: 'gm_harmonica' },
    { id: 'gm-bandoneon', label: 'GM Bandoneon', sound: 'gm_bandoneon' },
    { id: 'gm-sitar', label: 'GM Sitar', sound: 'gm_sitar' },
    { id: 'gm-banjo', label: 'GM Banjo', sound: 'gm_banjo' },
    { id: 'gm-shamisen', label: 'GM Shamisen', sound: 'gm_shamisen' },
    { id: 'gm-koto', label: 'GM Koto', sound: 'gm_koto' },
    { id: 'gm-kalimba', label: 'GM Kalimba', sound: 'gm_kalimba' },
    { id: 'gm-bagpipe', label: 'GM Bagpipe', sound: 'gm_bagpipe' },
    { id: 'gm-shanai', label: 'GM Shanai', sound: 'gm_shanai' },
    { id: 'gm-acoustic-bass', label: 'GM Acoustic bass', sound: 'gm_acoustic_bass' },
    { id: 'gm-electric-bass-finger', label: 'GM Finger bass', sound: 'gm_electric_bass_finger' },
    { id: 'gm-electric-bass-pick', label: 'GM Pick bass', sound: 'gm_electric_bass_pick' },
    { id: 'gm-fretless-bass', label: 'GM Fretless bass', sound: 'gm_fretless_bass' },
    { id: 'gm-slap-bass-1', label: 'GM Slap bass 1', sound: 'gm_slap_bass_1' },
    { id: 'gm-slap-bass-2', label: 'GM Slap bass 2', sound: 'gm_slap_bass_2' },
    { id: 'gm-synth-bass-1', label: 'GM Synth bass 1', sound: 'gm_synth_bass_1' },
    { id: 'gm-synth-bass-2', label: 'GM Synth bass 2', sound: 'gm_synth_bass_2' },
    { id: 'gm-contrabass', label: 'GM Contrabass', sound: 'gm_contrabass' },
    { id: 'gm-tuba', label: 'GM Tuba', sound: 'gm_tuba' },
    { id: 'gm-bassoon', label: 'GM Bassoon', sound: 'gm_bassoon' },
    { id: 'gm-lead-8-bass-lead', label: 'GM Bass lead', sound: 'gm_lead_8_bass_lead' },
    ...HIDDEN_PITCHED_CHOICES,
  ],
}
