import type { Kit } from './kits-types'

export const KITS_F: Kit[] = [

  // —— Techno ——
  {
    id: 'techno-system100',
    vibe: 'techno',
    name: 'System 100',
    description: 'Roland System 100 modular clicks',
    bpm: 128,
    drumsBank: 'RolandSystem100',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-rhythm-ace',
    vibe: 'lofi',
    name: 'Rhythm Ace',
    description: 'Ace auto-rhythm lo-fi character',
    bpm: 84,
    drumsBank: 'RhythmAce',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine', 'triangle'],
      fxBias: 'roomy',
      pinN: 0,
    },
  },

  // —— Techno ——
  {
    id: 'techno-ms404',
    vibe: 'techno',
    name: 'MS-404',
    description: 'Doepfer MS-404 acid-box drums',
    bpm: 130,
    drumsBank: 'DoepferMS404',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'high',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
      pinN: 0,
    },
  },
  {
    id: 'techno-sc-tom',
    vibe: 'techno',
    name: 'SC Tom',
    description: 'Sequential Circuits Tom punch',
    bpm: 128,
    drumsBank: 'SequentialCircuitsTom',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'filtered',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-jazz-kit',
    vibe: 'lofi',
    name: 'Jazz Kit',
    description: 'Dirt jazz acoustic-ish pocket',
    bpm: 90,
    drumsBank: 'dirt-jazz',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['piano', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'lofi-casio-sk1',
    vibe: 'lofi',
    name: 'Casio SK-1',
    description: 'Toy Casio SK-1 lo-fi swing',
    bpm: 82,
    drumsBank: 'CasioSK1',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Piano', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['piano', 'triangle'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'lofi-kr55',
    vibe: 'lofi',
    name: 'KR-55',
    description: 'Korg KR-55 vintage auto-rhythm',
    bpm: 84,
    drumsBank: 'KorgKR55',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Rim', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine', 'triangle'],
      fxBias: 'roomy',
    },
  },

  // —— Techno ——
  {
    id: 'techno-uzu-waves',
    vibe: 'techno',
    name: 'Uzu Waves',
    description: 'Uzu wavetable melodic techno',
    bpm: 128,
    drumsBank: 'uzu-wt',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Wave', role: 'lead' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['wt_digital', 'wt_vgame', 'sawtooth'],
      fxBias: 'filtered',
    },
  },

  // —— Ambient ——
  {
    id: 'ambient-vcsl-keys',
    vibe: 'ambient',
    name: 'VCSL Keys',
    description: 'VCSL marimba/kalimba ambient keys',
    bpm: 68,
    drumsBank: 'vcsl-keys',
    tracks: [
      { name: 'Pulse', role: 'drums' },
      { name: 'Shimmer', role: 'hihats' },
      { name: 'Marimba', role: 'pad' },
      { name: 'Kalimba', role: 'lead' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['marimba', 'kalimba', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-vcsl-organ',
    vibe: 'ambient',
    name: 'VCSL Organ',
    description: 'VCSL organ pad ambient wash',
    bpm: 64,
    drumsBank: 'vcsl-organ',
    tracks: [
      { name: 'Pulse', role: 'drums' },
      { name: 'Air', role: 'hihats' },
      { name: 'Organ', role: 'pad' },
      { name: 'Pipe', role: 'lead' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['organ_8inch', 'pipeorgan_quiet', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-tabla',
    vibe: 'ambient',
    name: 'Tabla Circle',
    description: 'Dirt tabla melodic perc circles',
    bpm: 72,
    drumsBank: 'dirt-tabla',
    tracks: [
      { name: 'Tabla', role: 'drums' },
      { name: 'Tabla2', role: 'hihats' },
      { name: 'Hit', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'perc_loop',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },

  // —— PR E leftover CDN (unused C-tier, not clones / no-kick / D) ——
  {
    id: 'lofi-ddm110',
    vibe: 'lofi',
    name: 'DDM-110 Soft',
    description: 'Korg DDM-110 vintage digital soft pocket',
    bpm: 86,
    drumsBank: 'KorgDDM110',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-tg33',
    vibe: 'ambient',
    name: 'TG-33 Soft',
    description: 'Yamaha TG-33 workstation ambient wash',
    bpm: 68,
    drumsBank: 'YamahaTG33',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Lead', role: 'lead' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine', 'triangle'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'house-d110',
    vibe: 'house',
    name: 'D-110 House',
    description: 'Roland D-110 workstation house drums',
    bpm: 120,
    drumsBank: 'RolandD110',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'piano'],
      fxBias: 'dry',
    },
  },
  {
    id: 'lofi-t3',
    vibe: 'lofi',
    name: 'T3 Grain',
    description: 'Korg T3 workstation lo-fi grain',
    bpm: 88,
    drumsBank: 'KorgT3',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Rim', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['piano', 'triangle'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'techno-krz',
    vibe: 'techno',
    name: 'KRZ Techno',
    description: 'Korg KRZ punchy techno workstation',
    bpm: 128,
    drumsBank: 'KorgKRZ',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
    },
  },
]
