import type { Kit } from './kits-types'

export const KITS_C: Kit[] = [
  {
    id: 'techno-minimal606',
    vibe: 'techno',
    name: 'Minimal 606',
    description: 'Sparse TR-606 ticks and snare',
    bpm: 128,
    drumsBank: 'RolandTR606',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ bd ~").bank("RolandTR606").gain(1.1)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("RolandTR606").gain(0.32)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ sd").bank("RolandTR606").gain(0.7)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ ~ g1>").sound("square").lpf(400).gain(0.68)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,eb3,g3]").sound("triangle").lpf(700).room(0.45).gain(0.24)' },
    ],
  },
  {
    id: 'techno-dmx-punch',
    vibe: 'techno',
    name: 'DMX Punch',
    description: 'Oberheim DMX body, industrial edge',
    bpm: 124,
    drumsBank: 'OberheimDMX',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("OberheimDMX").gain(1.15)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ hh").bank("OberheimDMX").gain(0.5)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("OberheimDMX").gain(0.8)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 eb2 f2 g2>").sound("sawtooth").lpf(550).gain(0.7)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 ~ g4 ~>").sound("square").delay(0.3).gain(0.2)' },
    ],
  },
  {
    id: 'lofi-mpc60',
    vibe: 'lofi',
    name: 'MPC60 Dust',
    description: 'Classic MPC60 boom-bap pocket',
    bpm: 86,
    drumsBank: 'AkaiMPC60',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ bd ~").bank("AkaiMPC60").gain(1.0)' },
      { name: 'Snare', role: 'fx', code: 's("~ sd ~ ~ ~ sd ~ ~").bank("AkaiMPC60").gain(0.75)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("AkaiMPC60").gain(0.28).lpf(4800)' },
      { name: 'Keys', role: 'pad', code: 'note("<[c3,eb3,g3] [f3,ab3,c4]>").sound("piano").lpf(1600).room(0.4).gain(0.3)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ f2 ~>").sound("sine").lpf(280).gain(0.55)' },
    ],
  },
  {
    id: 'lofi-sp12',
    vibe: 'lofi',
    name: 'SP-12 Grain',
    description: 'E-mu SP-12 crunch and warm keys',
    bpm: 90,
    drumsBank: 'EmuSP12',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ bd ~ ~ bd ~ ~").bank("EmuSP12").gain(0.95)' },
      { name: 'Rim', role: 'fx', code: 's("~ rim ~ ~ rim ~ ~ ~").bank("EmuSP12").gain(0.5)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("EmuSP12").gain(0.26).lpf(4200)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,e3,g3] [a2,c3,e3]>").sound("triangle").room(0.55).lpf(1300).gain(0.28)' },
      { name: 'Bass', role: 'bass', code: 'note("c2 ~ g1 ~ eb2 ~ f2 ~").sound("sawtooth").lpf(360).gain(0.5)' },
    ],
  },
  {
    id: 'lofi-casio-rz1',
    vibe: 'lofi',
    name: 'Casio RZ-1',
    description: 'Toy-box RZ-1 lo-fi swing',
    bpm: 82,
    drumsBank: 'CasioRZ1',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ bd ~ ~ ~ ~").bank("CasioRZ1").gain(0.9)' },
      { name: 'Clap', role: 'fx', code: 's("~ ~ cp ~ ~ ~ cp ~").bank("CasioRZ1").gain(0.55)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ hh").bank("CasioRZ1").gain(0.32).lpf(3800)' },
      { name: 'Piano', role: 'pad', code: 'note("<[c3,eb3,g3] [ab2,c3,eb3]>").sound("piano").room(0.6).attack(0.08).gain(0.26)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~>").sound("triangle").lpf(300).gain(0.5)' },
    ],
  },
  {
    id: 'ambient-lm1-haze',
    vibe: 'ambient',
    name: 'LM-1 Haze',
    description: 'Soft Linn LM-1 in the fog',
    bpm: 66,
    drumsBank: 'LinnLM1',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ ~").bank("LinnLM1").gain(0.4).lpf(750)' },
      { name: 'Hats', role: 'hihats', code: 's("~ hh ~ ~").bank("LinnLM1").gain(0.16).room(0.7)' },
      { name: 'Shaker', role: 'fx', code: 's("~ ~ sh ~").bank("LinnLM1").room(0.5).gain(0.22)' },
      { name: 'Pad', role: 'pad', code: 'note("<[c3,eb3,g3,bb3] [f3,ab3,c4]>").sound("sine").room(0.95).attack(0.9).gain(0.32)' },
      { name: 'Piano', role: 'lead', code: 'note("<c5 ~ eb5 ~>").sound("piano").room(0.7).gain(0.14)' },
    ],
  },
  {
    id: 'ambient-dr110-soft',
    vibe: 'ambient',
    name: 'DR-110 Soft',
    description: 'Boss DR-110 pulse under wide piano',
    bpm: 64,
    drumsBank: 'BossDR110',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd ~ ~ ~ ~ ~ ~ ~").bank("BossDR110").gain(0.45).lpf(650)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*4").bank("BossDR110").gain(0.12).room(0.55)' },
      { name: 'Ride', role: 'fx', code: 's("~ ~ rd ~").bank("BossDR110").room(0.75).gain(0.2)' },
      { name: 'Piano', role: 'pad', code: 'note("<[c3,e3,g3] [d3,f3,a3]>").sound("piano").room(0.9).attack(0.5).gain(0.28)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ ~ ~>").sound("sine").lpf(180).attack(0.4).gain(0.38)' },
    ],
  },
  {
    id: 'house-classic707',
    vibe: 'house',
    name: 'Classic 707',
    description: 'Four-on-floor TR-707 house',
    bpm: 122,
    drumsBank: 'RolandTR707',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("RolandTR707").gain(1.18)' },
      { name: 'Hats', role: 'hihats', code: 's("hh*8").bank("RolandTR707").gain("0.22 0.48 0.22 0.52 0.22 0.48 0.22 0.55")' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("RolandTR707").gain(0.88)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 ~ eb2 ~ f2 ~ g2 ~>").sound("sawtooth").lpf(520).gain(0.68)' },
      { name: 'Keys', role: 'pad', code: 'note("<[c3,e3,g3] [f3,a3,c4]>").sound("piano").lpf(1800).room(0.28).gain(0.24)' },
    ],
  },
  {
    id: 'house-505-groove',
    vibe: 'house',
    name: '505 Groove',
    description: 'Light TR-505 house pocket',
    bpm: 120,
    drumsBank: 'RolandTR505',
    tracks: [
      { name: 'Kick', role: 'drums', code: 's("bd*4").bank("RolandTR505").gain(1.1)' },
      { name: 'Hats', role: 'hihats', code: 's("[hh oh]*4").bank("RolandTR505").gain(0.4)' },
      { name: 'Clap', role: 'fx', code: 's("~ cp ~ cp").bank("RolandTR505").gain(0.78)' },
      { name: 'Bass', role: 'bass', code: 'note("c2 eb2 f2 g2").sound("square").lpf(560).gain(0.62)' },
      { name: 'Lead', role: 'lead', code: 'note("<c5 eb5 g5>*2").sound("triangle").delay(0.22).gain(0.2)' },
    ],
  },
  {
    id: 'house-727-latin',
    vibe: 'house',
    name: '727 Latin',
    description: 'TR-727 percussion house (perc + shaker)',
    bpm: 118,
    drumsBank: 'RolandTR727',
    tracks: [
      { name: 'Perc', role: 'drums', code: 's("perc*4").bank("RolandTR727").gain(0.85)' },
      { name: 'Shaker', role: 'hihats', code: 's("sh*8").bank("RolandTR727").gain(0.45)' },
      { name: 'Conga', role: 'fx', code: 's("~ perc ~ perc").bank("RolandTR727").room(0.25).gain(0.55)' },
      { name: 'Bass', role: 'bass', code: 'note("<c2 c2 g1 g1>").sound("sawtooth").lpf(480).gain(0.65)' },
      { name: 'Pad', role: 'pad', code: 'note("[c3,e3,g3]").sound("sine").room(0.35).gain(0.22)' },
    ],
  }
]
