import type { Kit } from './kits-types'

export const KITS_C: Kit[] = [

  // —— Techno ——
  {
    id: 'techno-minimal606',
    vibe: 'techno',
    name: 'Minimal 606',
    description: 'Sparse TR-606 ticks and snare',
    bpm: 128,
    drumsBank: 'RolandTR606',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Snare', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'filtered',
    },
  },
  {
    id: 'techno-dmx-punch',
    vibe: 'techno',
    name: 'DMX Punch',
    description: 'Oberheim DMX body, industrial edge',
    bpm: 124,
    drumsBank: 'OberheimDMX',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'square'],
      fxBias: 'filtered',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-mpc60',
    vibe: 'lofi',
    name: 'MPC60 Dust',
    description: 'Classic MPC60 boom-bap pocket',
    bpm: 86,
    drumsBank: 'AkaiMPC60',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['piano', 'sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'lofi-sp12',
    vibe: 'lofi',
    name: 'SP-12 Grain',
    description: 'E-mu SP-12 crunch and warm keys',
    bpm: 90,
    drumsBank: 'EmuSP12',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Rim', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sawtooth'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'lofi-casio-rz1',
    vibe: 'lofi',
    name: 'Casio RZ-1',
    description: 'Toy-box RZ-1 lo-fi swing',
    bpm: 82,
    drumsBank: 'CasioRZ1',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Clap', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Piano', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['piano', 'triangle'],
      fxBias: 'roomy',
    },
  },

  // —— Ambient ——
  {
    id: 'ambient-lm1-haze',
    vibe: 'ambient',
    name: 'LM-1 Haze',
    description: 'Soft Linn LM-1 in the fog',
    bpm: 66,
    drumsBank: 'LinnLM1',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Shaker', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Piano', role: 'lead' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['sine', 'piano'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'ambient-dr110-soft',
    vibe: 'ambient',
    name: 'DR-110 Soft',
    description: 'Boss DR-110 pulse under wide piano',
    bpm: 64,
    drumsBank: 'BossDR110',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Ride', role: 'fx' },
      { name: 'Piano', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'sparse',
      density: 'low',
      root: 'c',
      scale: 'dorian',
      melodicSounds: ['piano', 'sine'],
      fxBias: 'roomy',
    },
  },

  // —— House ——
  {
    id: 'house-classic707',
    vibe: 'house',
    name: 'Classic 707',
    description: 'Four-on-floor TR-707 house',
    bpm: 122,
    drumsBank: 'RolandTR707',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Keys', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'piano'],
      fxBias: 'dry',
    },
  },
  {
    id: 'house-505-groove',
    vibe: 'house',
    name: '505 Groove',
    description: 'Light TR-505 house pocket',
    bpm: 120,
    drumsBank: 'RolandTR505',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'dry',
    },
  },
  {
    id: 'house-727-latin',
    vibe: 'house',
    name: '727 Latin',
    description: 'TR-727 percussion house (perc + shaker)',
    bpm: 118,
    drumsBank: 'RolandTR727',
    tracks: [
      { name: 'Perc', role: 'drums' },
      { name: 'Shaker', role: 'hihats' },
      { name: 'Conga', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'perc_loop',
      density: 'mid',
      root: 'c',
      scale: 'major',
      melodicSounds: ['sawtooth', 'sine'],
      fxBias: 'dry',
    },
  },
]
