import type { Kit } from './kits-types'

export const KITS_A: Kit[] = [

  // —— Techno ——
  {
    id: 'techno-punch909',
    vibe: 'techno',
    name: 'Punch 909',
    description: 'Classic punchy TR-909 kit',
    bpm: 128,
    drumsBank: 'RolandTR909',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hi-Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sawtooth', 'triangle'],
      fxBias: 'filtered',
    },
  },
  {
    id: 'techno-boom808',
    vibe: 'techno',
    name: 'Boom 808',
    description: 'Deep 808 body, darker hats',
    bpm: 130,
    drumsBank: 'RolandTR808',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hi-Hats', role: 'hihats' },
      { name: 'Clap', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Lead', role: 'lead' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'high',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine', 'square'],
      fxBias: 'filtered',
    },
  },
  {
    id: 'techno-crisp-linn',
    vibe: 'techno',
    name: 'Crisp Linn',
    description: 'Tight LinnDrum percussion',
    bpm: 126,
    drumsBank: 'LinnDrum',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hi-Hats', role: 'hihats' },
      { name: 'Rim', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Arp', role: 'arp' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['square', 'triangle'],
      fxBias: 'filtered',
    },
  },
  {
    id: 'techno-soft-cr78',
    vibe: 'techno',
    name: 'Soft CR78',
    description: 'Vintage Compurhythm texture',
    bpm: 120,
    drumsBank: 'RolandCompurhythm78',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hi-Hats', role: 'hihats' },
      { name: 'Perc', role: 'fx' },
      { name: 'Bass', role: 'bass' },
      { name: 'Pad', role: 'pad' },
    ],
    shuffle: {
      groove: 'four_on_floor',
      density: 'mid',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sine'],
      fxBias: 'filtered',
    },
  },

  // —— Lo-fi ——
  {
    id: 'lofi-dusty808',
    vibe: 'lofi',
    name: 'Dusty 808',
    description: 'Soft boom-bap 808',
    bpm: 85,
    drumsBank: 'RolandTR808',
    tracks: [
      { name: 'Drums', role: 'drums' },
      { name: 'Rim', role: 'fx' },
      { name: 'Hi-Hats', role: 'hihats' },
      { name: 'Chords', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'breakbeat',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sawtooth'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'lofi-vinyl-linn',
    vibe: 'lofi',
    name: 'Vinyl Linn',
    description: 'Crisp breaks, warm keys',
    bpm: 88,
    drumsBank: 'LinnDrum',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Snare', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Keys', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine', 'triangle'],
      fxBias: 'filtered',
    },
  },
  {
    id: 'lofi-soft-cr78',
    vibe: 'lofi',
    name: 'Tape CR78',
    description: 'Round vintage kit',
    bpm: 80,
    drumsBank: 'RolandCompurhythm78',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Perc', role: 'fx' },
      { name: 'Pad', role: 'pad' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['sine'],
      fxBias: 'roomy',
    },
  },
  {
    id: 'lofi-909-chill',
    vibe: 'lofi',
    name: 'Chill 909',
    description: '909 swung soft',
    bpm: 92,
    drumsBank: 'RolandTR909',
    tracks: [
      { name: 'Kick', role: 'drums' },
      { name: 'Clap', role: 'fx' },
      { name: 'Hats', role: 'hihats' },
      { name: 'Lead', role: 'lead' },
      { name: 'Bass', role: 'bass' },
    ],
    shuffle: {
      groove: 'halftime',
      density: 'low',
      root: 'c',
      scale: 'minor',
      melodicSounds: ['triangle', 'sawtooth'],
      fxBias: 'roomy',
    },
  },
]
